from Language_Early_Stage import *
IF,POSSIBILITY,EXISTS,IN,MULTIPLE,FORMS,THEN,CHOOSE,THE,POSSIBILITY,WITH,BETTER,ACCURATE,EFFECTS,THAN,THE,NEUTRAL,OR,NEGATIVE,OUTCOME
MAKE,PROCESS,FOR,RECALL,PROCEDURE,TO,RECOGNIZE,COLLECTED,DATA,WITH,MANY,FORMS,FOR,TYPES,AND,CLASSES
EACH,POSSIBILITY,RECOGNIZED,MUST,BE,MADE,INTO,REFERENCE,DATA,FOR,RECALL,METHOD,TO,HAPPEN
WHEN,REFERENCE,DATA,IS,GATHERED,MAKE,POSSIBILITY,TO,GATHER,DATA,FROM,REFERENCE,SOURCE,RELATING,TO,POSITION,AND,POINT,FOR,ORIGIN,TO,OUTPUT,KNOWN,EFFECT