from Language_Early_Stage import *
from Language_Extension_001 import *
IF,CHOICE,MEASUREMENT,IS,INCHES
print("THE CHOICE FOR MEASUREMENT IS INCHES")
IF,ELSE,THEN,DETERMINE,IF,MEASUREMENT,IS,CENTIMETERS
IF,CHOICE,MEASUREMENT,IS,CENTIMETERS
print("THE CHOICE FOR MEASUREMENT IS CENTIMETERS")