from examplescript import *
print(CREATE,NEW,FREQUENCY,ANALYZER)
print(FREQUENCY,ANALYZER,SHALL,BE,MADE,FOR,PROCESSING,CALCULATED,FUNCTIONS,OF,FREQUENCY,DATA,FROM,INCOMING,INPUT,OF,CALCULATED,LOCATION,PATH,DATA,STORED,WITHIN,ASUNAOS)
print(FREQUENCY,ANALYZER,SHALL,PREDICT,OUTCOMES,OF,UPCOMING,DATA,USING,PREVIOUS,DATA,ANALYZED,FROM,FREQUENCY,ANALYZER)
print(FREQUENCY,ANALYZER,SHALL,NOT,CALCULATE,READINGS,FROM,MATERIAL,DATA,WITHIN,OPERATING,SYSTEM,IF,MATERIAL,DATA,EXISTS)
print(FREQUENCY,DATA,MAY,CALCULATE,REACH,OF,FREQUENCY,AS,WELL,AS,BEGINNING,INPUT,OF,FREQUENCY,DATA,LOCATION,WHILE,USING,ORIGIN)