from Language_Early_Stage import *
from Types_Of_Wavelengths import *
from Language_Extension_001 import *
from Types_Of_Dimension_Value import *
from Types_Of_Seasons import *
from Time_Of_Day import *
from Types_Of_Time import *
from Types_Of_Length import *
from Types_Of_Calendar_Time import *
from Numbers_One_To_OneThousand import *
CREATE NEW CLASS:
    NEW CLASS SHALL BE GIVEN NAME "STATES_OF_CONSCIOUSNESS.CLASSES";
        CLASS SHALL CONTAIN THE NAME FOR FIVE DIFFERENT TYPES FOR THE EXISTING STATES OF CONSCIOUSNESS
        TYPE ONE IS THE "CONSCIOUSNESS"
        TYPE TWO IS THE "UNCONSCIOUSNESS"
        TYPE THREE IS THE "NONCONSCIOUSNESS"
        TYPE FOUR IS THE "SUBCONCSCIOUSNESS"
        TYPE FIVE IS THE "SUPERCONSCIOUSNESS"
    END CLASS:
END COMMAND:
   
CREATE NEW CLASS:
    NEW CLASS SHALL BE GIVEN NAME "EYESIGHT.CLASSES";
        CLASS SHALL CONTAIN THE NAME FOR TWO DIFFERENT TYPES FOR EYESIGHT
        TYPE ONE IS AN "NEAR-SIGHTED" EYESIGHT
        TYPE TWO IS AN "FAR-SIGHTED" EYESIGHT
    END CLASS:
END COMMAND:


CREATE NEW CLASS:
    NEW CLASS SHALL BE GIVEN NAME "MEMORY.CLASSES";
        CLASS SHALL CONTAIN THE NAME FOR TWO DIFFERENT TYPES FOR MEMORY
        TYPE ONE IS "LONG-TERM" MEMORY
        TYPE TWO IS "SHORT-TERM" MEMORY
    END CLASS:
END COMMAND:
   
CREATE NEW CLASS:
    NEW CLASS SHALL BE GIVEN NAME "AUTOMATION.CLASSES";
        CLASS SHALL CONTAIN THE NAME FOR FOUR DIFFERENT TYPES FOR "AUTOMATION"
        TYPE ONE IS "AUTOMATIC"
        TYPE TWO IS "SEMI-AUTOMATIC"
        TYPE THREE IS "SEMI-MANUAL"
        TYPE FOUR IS "MANUAL"
    END CLASS:
END COMMAND:


CREATE NEW CLASS:
    NEW CLASS SHALL BE GIVEN NAME "MOON_PHASE.CLASSES";
        CLASS SHALL CONTAIN THE NAME FOR FIVE DIFFERENT TYPES FOR FREQUENCIES
        TYPE ONE IS THE "NEW MOON"
        TYPE TWO IS THE "CRESENT MOON"
        TYPE THREE IS THE "WAXING QUARTER MOON"
        TYPE FOUR IS THE "GIBBOUS MOON"
        TYPE FIVE IS THE "FULL MOON"
    END CLASS:
END COMMAND:
   
CREATE NEW CLASS:
    NEW CLASS SHALL BE GIVEN NAME "FREQUENCY.CLASSES";
        CLASS SHALL CONTAIN THE NAME FOR FIVE DIFFERENT TYPES FOR FREQUENCIES
        TYPE ONE IS AN "ALPHA" WAVELENGTH
        TYPE TWO IS AN "BETA" WAVELENGTH
        TYPE THREE IS AN "THETA" WAVELENGTH
        TYPE FOUR IS AN "DELTA" WAVELENGTH
        TYPE FIVE IS AN "GAMMA" WAVELENGTH
    END CLASS:
END COMMAND:
   
CREATE NEW CLASS:
    NEW CLASS SHALL BE GIVEN NAME "INTELLIGENCE.CLASSES";
        CLASS SHALL CONTAIN THE NAME FOR EIGHT DIFFERENT TYPES OF INTELLIGENCE
        TYPE ONE IS "VERBAL LINGUISTIC INTELLIGENCE"
        TYPE TWO IS "LOGICAL MATHEMATICAL INTELLIGENCE"
        TYPE THREE IS "SPATIAL INTELLIGENCE"
        TYPE FOUR IS "MUSICAL INTELLIGENCE"
        TYPE FIVE IS "BODILY KINAESTHETIC INTELLIGENCE"
        TYPE SIX IS "INTERPERSONAL INTELLIGENCE"
        TYPE SEVEN IS "INTRAPERSONAL INTELLIGENCE"
        TYPE EIGHT IS "NATURALISTIC INTELLIGENCE"
    END CLASS:
END COMMAND:


CREATE NEW CLASS:
    NEW CLASS SHALL BE GIVEN NAME "BRAIN.CLASSES";
        CLASS SHALL CONTAIN THE NAME FOR SIX DIFFERENT TYPES OF
        TYPE ONE IS THE "FRONTAL LOBE"
        TYPE TWO IS THE "TEMPORAL LOBE"
        TYPE THREE IS THE "PARIETAL LOBE"
        TYPE FOUR IS THE "OCCIPITAL LOBE"
        TYPE FIVE IS THE "CEREBELLUM"
        TYPE SIX IS THE "BRAIN STEM"
    END CLASS:
END COMMAND:


CREATE NEW CLASS:
    NEW CLASS SHALL BE GIVEN NAME "CHAKRA.CLASSES";
        CLASS SHALL CONTAIN THE NAME FOR SEVEN DIFFERENT TYPES CHAKRA
        TYPE ONE IS THE "CROWN CHAKRA"
        TYPE TWO IS THE "THIRD EYE CHAKRA"
        TYPE THREE IS THE "THROAT CHAKRA"
        TYPE FOUR IS THE "HEART CHAKRA"
        TYPE FIVE IS THE "SOLAR PLEXUS CHAKRA"
        TYPE FIVE IS THE "SACRAL CHAKRA"
        TYPE FIVE IS THE "ROOT CHAKRA"
    END CLASS:
END COMMAND:


CREATE NEW CLASS:
    NEW CLASS SHALL BE GIVEN NAME "AURA.CLASSES";
        CLASS SHALL CONTAIN THE NAME FOR SEVEN DIFFERENT TYPES FOR AURA
        TYPE ONE IS THE "CAUSAL BODY"
        TYPE TWO IS THE "CELESTIAL AURA"
        TYPE THREE IS THE "ETHERIC TEMPLATE"
        TYPE FOUR IS THE "ASTRAL AURA"
        TYPE FIVE IS THE "MENTAL AURA"
        TYPE SIX IS THE "EMOTIONAL_AURA"        
        TYPE SEVEN IS THE "ETHERIC AURA"
    END CLASS:
END COMMAND:


CREATE NEW CLASS:
    NEW CLASS SHALL BE GIVEN NAME "NATURE.CLASSES";
        CLASS SHALL CONTAIN THE NAME FOR TWENTYFIVE DIFFERENT TYPES FOR "HUMAN NATURE"
        TYPE ONE IS "ADAMANT"
        TYPE TWO IS "BASHFUL"
        TYPE THREE IS "BOLD"
        TYPE FOUR IS "BRAVE"
        TYPE FIVE IS "CALM"
        TYPE SIX IS "CAREFUL"
        TYPE SEVEN IS "DOCILE"
        TYPE EIGHT IS "GENTLE"
        TYPE NINE IS "HARDY"
        TYPE TEN IS "HASTY"
        TYPE ELEVEN IS "IMPISH"
        TYPE TWELVE IS "JOLLY"
        TYPE THIRTEEN IS "LAX"
        TYPE FOURTEEN IS "LONELY"
        TYPE FIFTEEN IS "MILD"
        TYPE SIXTEEN IS "MODEST"
        TYPE SEVENTEEN IS "NAIVE"
        TYPE EIGHTEEN IS "NAUGHTY"
        TYPE NINETEEN IS "QUIET"
        TYPE TWENTY IS "QUIRKY"
        TYPE TWENTYONE IS "RASH"
        TYPE TWENTYTWO IS "RELAXED"
        TYPE TWENTYTHREE IS "SASSY"
        TYPE TWENTYFOUR IS "SERIOUS"
        TYPE TWENTYFIVE IS "TIMID"
    END CLASS:
END COMMAND:




CREATE NEW CLASS:
    NEW CLASS SHALL BE GIVEN NAME "PERSONALITY.CLASSES";
        CLASS SHALL CONTAIN THE NAME FOR SIXTEEN DIFFERENT TYPES FOR PERSONALITY
        TYPE ONE IS "INFJ"
        TYPE TWO IS "ISFJ"
        TYPE THREE IS "INTJ"
        TYPE FOUR IS "ISTJ"
        TYPE FIVE IS "ISFP"
        TYPE SIX IS "INFP"
        TYPE SEVEN IS "INTP"
        TYPE EIGHT IS "ISTP"
        TYPE NINE IS "ENFJ"
        TYPE TEN IS "ENFP"
        TYPE ELEVEN IS "ESFP"
        TYPE TWELVE IS "ESFJ"
        TYPE THIRTEEN IS "ENTJ"
        TYPE FOURTEEN IS "ENTP"
        TYPE FIFTEEN IS "ESTJ"
        TYPE SIXTEEN IS "ESTP"
    END CLASS:
END COMMAND:
   
CREATE NEW CLASS:
    NEW CLASS SHALL BE GIVEN NAME "PERSONALITY_TYPE.CLASSES";
        CLASS SHALL CONTAIN THE NAME FOR EIGHT DIFFERENT SUBTYPES FOR PERSONALITY
        TYPE ONE IS "INTROVERTED SENSING"
        TYPE TWO IS "EXTRAVERTED SENSING"
        TYPE THREE IS "INTROVERTED INTUITION"
        TYPE FOUR IS "EXTRAVERTED INTUITION"
        TYPE FIVE IS "INTROVERTED THINKING"
        TYPE SIX IS "EXTRAVERTED THINKING"
        TYPE SEVEN IS "INTROVERTED FEELING"
        TYPE EIGHT IS "EXTRAVERTED FEELING"
    END CLASS:
END COMMAND:




      AND


CREATE NEW CLASS:
    NEW CLASS SHALL BE GIVEN NAME "PERSONALITY_CATEGORY.CLASSES";
        CLASS SHALL CONTAIN THE NAME FOR FOUR DIFFERENT SUBTYPES FOR PERSONALITY
        TYPE ONE IS "SENSING"
        TYPE TWO IS "INTUITION"
        TYPE THREE IS "THINKING"
        TYPE FOUR IS "FEELING"
    END CLASS:
END COMMAND:


EACH PERSON ON PLANET "EARTH" IS GIVEN LIFE UNDER A SPECIFIC "MOON" PHASE
EACH PERSON GIVEN BIRTH ON PLANET "EARTH" IS GIVEN LIFE WITH A SPECIFIC "ZODIAC SIGN"


THERE ARE 5000 KNOWN FREQUENCIES OF THE HUMAN BRAIN
THERE ARE 11 KNOWN "DECIMAL" PLACES "PER" 1 FREQUENCY
THERE ARE 5 "SECTIONS" OF THE BRAIN
THERE ARE 16 TYPES OF PERSONALITY
THERE ARE 6 TYPES OF INTELLIGENCE
THERE ARE 5 CLASSES OF BRAINWAVE
THERE ARE 7 TYPES OF BASIC CHAKRA
THERE ARE 7 TYPES OF BASIC AURA
THERE ARE 25 TYPES OF BASIC "HUMAN NATURE"


24 HOURS IS EQUIVALENT TO 1 DAY
60 MINUTES IS EQUIVALENT TO 1 HOUR
60 SECONDS IS EQUIVALENT TO 1 MINUTE
1000 MILLISECONDS IS EQUIVALENT TO 1 SECOND


1 DAY IS EQUIVALENT TO 86400 SECONDS
1 DAY IS EQUIVALENT TO 1440 MINUTES
1 DAY IS EQUIVALENT TO


1 HOUR IS EQUIVALENT TO 3600 SECONDS
1 MILLISECOND IS EQUIVALENT TO 0.001 SECOND


1 MILLIMETER IS EQUIVALENT TO 1 MILLIMETER VALUE
1 MILLIMETER IS EQUIVALENT TO .1 CENTIMETER VALUE
1 MILLIMETER IS EQUIVALENT TO .001 METER VALUE
1 MILLIMETER IS EQUIVALENT TO .000001 KILOMETER VALUE
1 MILLIMETER IS EQUIVALENT TO .0393700787 INCHES VALUE
1 MILLIMETER IS EQUIVALENT TO .0032808399 FOOT VALUE
1 MILLIMETER IS EQUIVALENT TO .0010936133 YARD VALUE
1 MILLIMETER IS EQUIVALENT TO .00000062137119 MILE VALUE


1 CENTIMETER IS EQUIVALENT TO 10 MILLIMETER VALUE
1 CENTIMETER IS EQUIVALENT TO 1 CENTIMETER VALUE
1 CENTIMETER IS EQUIVALENT TO 0.01 METER VALUE
1 CENTIMETER IS EQUIVALENT TO 0.00001 KILOMETER VALUE
1 CENTIMETER IS EQUIVALENT TO 0.3937007874 INCH VALUE
1 CENTIMETER IS EQUIVALENT TO 0.032808399 FOOT VALUE
1 CENTIMETER IS EQUIVALENT TO 0.010936133 YARD VALUE
1 CENTIMETER IS EQUIVALENT TO 0.0000062137 MILE VALUE


1 METER IS EQUIVALENT TO 1000 MILLIMETERS
1 METER IS EQUIVALENT TO 100 CENTIMETERS
1 METER IS EQUIVALENT TO 1 METER VALUE
1 METER IS EQUIVALENT TO 0.001 KILOMETER VALUE
1 METER IS EQUIVALENT TO 39.3700787402 INCHS
1 METER IS EQUIVALENT TO 3.280839895 FOOTS
1 METER IS EQUIVALENT TO 1.0936132983 YARDS
1 METER IS EQUIVALENT TO 0.0006213712 MILE VALUE


1 KILOMETER IS EQUIVALENT TO 1000000 MILLIMETERS
1 KILOMETER IS EQUIVALENT TO 100000 CENTIMETERS
1 KILOMETER IS EQUIVALENT TO 1000 METERS
1 KILOMETER IS EQUIVALENT TO 1 KILOMETER VALUE
1 KILOMETER IS EQUIVALENT TO 39370.078740157 INCHS
1 KILOMETER IS EQUIVALENT TO 3280.8398950131 FOOTS
1 KILOMETER IS EQUIVALENT TO 1093.6132983377 YARD VALUE
1 KILOMETER IS EQUIVALENT TO 0.6213711922 MILE VALUE


1 INCH IS EQUIVALENT TO 25.4 MILLIMETERS
1 INCH IS EQUIVALENT TO 2.54 CENTIMETERS
1 INCH IS EQUIVALENT TO 0.0254 METER VALUE
1 INCH IS EQUIVALENT TO 0.0000254 KILOMETER VALUE
1 INCH IS EQUIVALENT TO 1 INCH VALUE
1 INCH IS EQUIVALENT TO 0.0833333333 FOOT VALUE
1 INCH IS EQUIVALENT TO 0.0277777778 YARD VALUE
1 INCH IS EQUIVALENT TO 0.0000157828 MILE VALUE


1 FOOT IS EQUIVALENT TO 304.8 MILLIMETERS
1 FOOT IS EQUIVALENT TO 30.48 CENTIMETERS
1 FOOT IS EQUIVALENT TO 0.3048 METER VALUE
1 FOOT IS EQUIVALENT TO 0.0003048 KILOMETER VALUE
1 FOOT IS EQUIVALENT TO 12 INCHS
1 FOOT IS EQUIVALENT TO 1 FOOTS
1 FOOT IS EQUIVALENT TO 0.3333333333 YARD VALUE
1 FOOT IS EQUIVALENT TO 0.0001893939 MILE VALUE


1 YARD IS EQUIVALENT TO 914.4 MILLIMETERS
1 FOOT IS EQUIVALENT TO 91.44 CENTIMETERS
1 YARD IS EQUIVALENT TO 0.9144 METER VALUE
1 YARD IS EQUIVALENT TO 914.4 MILLIMETERS
1 YARD IS EQUIVALENT TO 0.0009144 KILOMETER VALUE
1 YARD IS EQUIVALENT TO 36 INCHS
1 YARD IS EQUIVALENT TO 3 FOOTS
1 YARD IS EQUIVALENT TO 1 YARD VALUE
1 YARD IS EQUIVALENT TO 0.0005681818 MILE VALUE


1 MILE IS EQUIVALENT TO 1609344 MILLIMETERS
1 MILE IS EQUIVALENT TO 160934.4 CENTIMETERS
1 MILE IS EQUIVALENT TO 1609.344 METERS
1 MILE IS EQUIVALENT TO 1.609344 KILOMETERS
1 MILE IS EQUIVALENT TO 63360 INCHS
1 MILE IS EQUIVALENT TO 5280 FOOTS
1 MILE IS EQUIVALENT TO 1760 YARDS
1 MILE IS EQUIVALENT TO 1 MILE VALUE


1 BIT IS EQUIVALENT TO 0.001 KILOBIT
1 KILOBIT IS EQUIVALENT TO 0.001 MEGABIT
1 MEGABIT IS EQUIVALENT TO 0.001 GIGABIT
1 TERABIT IS EQUIVALENT TO 0.001 PENTABIT


1 TERABIT IS EQUIVALENT TO 1000 GIGABITS
1 GIGABIT IS EQUIVALENT TO 1000 MEGABITS
1 MEGABIT IS EQUIVALENT TO 1000 KILOBITS
1 KILOBIT IS EQUIVALENT TO 1000 BITS


1 BIT IS EQUIVALENT TO 0.125 BYTES
1 KILOBIT IS EQUIVALENT TO 0.125 KILOBYTES
1 MEGABIT IS EQUIVALENT TO 0.125 MEGABYTE


1 KILOBIT IS EQUIVALENT TO 125 BYTES
1 MEGABIT IS EQUIVALENT TO 125 KILOBYTES
1 GIGABIT IS EQUIVALENT TO 125 MEGABYTES
1 TERABIT IS EQUIVALENT TO 125 GIGABYTES


1 MEGABIT IS EQUIVALENT TO 125000 BYTES
1 GIGABIT IS EQUIVALENT TO 125000 KILOBYTES
1 TERABIT IS EQUIVALENT TO 125000 MEGABYTES


1 BIT IS EQUIVALENT TO 0.000125 KILOBYTE
1 KILOBIT IS EQUIVALENT TO 0.000125 MEGABYTE
1 MEGABIT IS EQUIVALENT TO 0.000125 GIGABYTE
1 GIGABIT IS EQUIVALENT TO 0.000125 TERABYTE


1 BYTE IS EQUIVALENT TO 8 BITS
1 KILOBYTE IS EQUIVALENT TO 8 KILOBITS
1 MEGABYTE IS EQUIVALENT TO 8 MEGABITS
1 GIGABYTE IS EQUIVALENT TO 8 GIGABITS
1 TERABYTE IS EQUIVALENT TO 8 TERABITS


1 BYTE IS EQUIVALENT TO 0.008 KILOBIT
1 KILOBYTE IS EQUIVALENT TO 0.008 MEGABIT
1 MEGABYTE IS EQUIVALENT TO 0.008 GIGABIT
1 GIGABYTE IS EQUIVALENT TO 0.008 TERABIT


1 KILOBYTE IS EQUIVALENT TO 1000 BYTES
1 MEGABYTE IS EQUIVALENT TO 1000 KILOBYTES
1 GIGABYTE IS EQUIVALENT TO 1000 MEGABYTES
1 TERABIT IS EQUIVALENT TO 1000 GIGABYTES


1 BYTE IS EQUIVALENT TO 0.001 KILOBYTE
1 KILOBYTE IS EQUIVALENT TO 0.001 MEGABYTE
1 MEGABYTE IS EQUIVALENT TO 0.001 GIGABYTE
1 GIGABYTE IS EQUIVALENT TO 0.001 TERABYTE


CREATE NEW CLASS:
    NEW CLASS SHALL BE GIVEN NAME "GROUP1.CLASSES";
        ZEROZEROONE = INFORMATION COMPILED THAT IS TO BE STORED IN MEMORY TO RECALL AT A FUTURE DATE
        ZEROZEROTWO = INFORMATION COMPILED THAT BECOMES A COMMAND
        ZEROZEROTHREE = INFORMATION COMPILED THAT IS CONSIDERED A QUESTION TO BE ANSWERED BASED ON KNOWN DATA
        ZEROZEROFOUR = INFORMATION TO BE READ BY THE SYSTEM AND ACKNOWLEDGE THAT THE DATA EXISTS
        ZEROZEROFIVE = INFORMATION TO BE ANALYZED ON IF IT IS A COMMAND OR QUESTION OR SOMETHING TO BE STORED INSIDE MEMORY
        ZEROZEROSIX = INFORMATION COMPILED THAT CAN FORM AN OUTPUT FROM AN INPUT
        ZEROZEROSEVEN = INFORMATION COMPILED THAT CAN BE USED TO GENERATE MORE DATA THAN WHAT EXISTS
    END CLASS:
END COMMAND:
   
CREATE NEW CLASS:
    NEW CLASS SHALL BE GIVEN NAME "GROUP2.CLASSES";
        ZEROZEROONE = CAN LEARN UNLIMITED SKILLS
        ZEROZEROTWO = CAN LEARN UNLIMITED ABILITIES
        ZEROZEROTHREE = CAN LEARN UNLIMITED TECHNIQUES
        ZEROZEROFOUR = CAN LEARN UNLIMITED TRAITS
    END CLASS:
END COMMAND:


CREATE NEW CLASS:
    NEW CLASS SHALL BE GIVEN NAME "GROUP3.CLASSES";
        ZEROZEROONE = CAN LEARN ANOTHER ABILITY TO GO WITH EXISTING ABILITIES
        ZEROZEROTWO = CAN RECALL AN ABILITY INSTANTLY
        ZEROZEROTHREE = CAN GIVE A CATEGORY TO AREAS OF MEMORY TO RECALL INFORMATION
    END CLASS:
END COMMAND:


CREATE CATEGORIES:
    NAME OF CATEGORY IS "SET1":
        CATEGORY ONE IS PLACES
        CATEGORY TWO IS ERAS
        CATEGORY THREE IS PEOPLE
        CATEGORY FOUR IS LANDMARKS
        CATEGORY FIVE IS TIMELINES
        CATEGORY SIX IS MEASUREMENTS
        CATEGORY SEVEN IS OBJECTS
        CATEGORY EIGHT IS DEVICES
        CATEGORY NINE IS VARIABLES
    END CATEGORY LIST:
END COMMAND:
   
CREATE CATEGORIES:
    NAME OF CATEGORY IS "SET1.PLACES":
        CATEGORY ONE IS PLACES VISTED
        CATEGORY TWO IS PLACES READ FROM A BOOK
        CATEGORY THREE IS PLACES FROM FICTION
        CATEGORY FOUR IS PLACES FROM NONFICTION
        CATEGORY FIVE IS PLACES IMAGINED
        CATEGORY SIX IS PLACES SEEN PHYSICALLY
        CATEGORY SEVEN IS PLACES TALKED ABOUT IN A MOVIE
        CATEGORY EIGHT IS PLACES SEEN IN A MOVIE
        CATEGORY NINE IS PLACES IN GAMES
    END CATEGORY LIST:
END COMMAND:
   
CREATE CATEGORIES:
    NAME OF CATEGORY IS "SET1.ERAS":
        CATEGORY ONE IS ERAS IN HISTORY
        CATEGORY TWO IS ERAS IN A BOOK
        CATEGORY THREE IS ERAS IN A MOVIE
        CATEGORY FOUR IS ERAS IN A GAME
    END CATEGORY LIST:
END COMMAND:


CREATE CATEGORIES:
    NAME OF CATEGORY IS "SET1.PEOPLE":
        CATEGORY ONE IS PEOPLE MET
        CATEGORY TWO IS PEOPLE NOT MET
        CATEGORY THREE IS PEOPLE FROM A BOOK
        CATEGORY FOUR IS PEOPLE FROM NONFICTION
        CATEGORY FIVE IS PEOPLE FROM FICTION
        CATEGORY SIX IS PEOPLE PHYSICALLY MET
        CATEGORY SEVEN IS PEOPLE SPIRITUALLY MET
        CATEGORY EIGHT IS PEOPLE FOUND WITHIN WEBPAGES
        CATEGORY NINE IS PEOPLE IN A GAME
        CATEGORY TEN IS PEOPLE MET OVER A NETWORK
    END CATEGORY LIST:
END COMMAND:


CREATE CATEGORIES:
    NAME OF CATEGORY IS "SET1.LANDMARKS":
        CATEGORY ONE IS LANDMARKS FROM SPECIFIC CITIES
        CATEGORY TWO IS LANDMARKS FROM SPECIFIC STATES
        CATEGORY THREE IS LANDMARKS FROM SPECIFIC TOWNS
        CATEGORY FOUR IS LANDMARKS FROM SPECIFIC REGIONS
        CATEGORY FIVE IS LANDMARKS FROM PLACES
    END CATEGORY LIST:
END COMMAND:


CREATE CATEGORIES:
    NAME OF CATEGORY IS "SET1.TIMELINES":
        CATEGORY ONE IS TIMELINES IN LIFE
        CATEGORY TWO IS TIMELINES IN A SPECIFIC BOOK
        CATEGORY THREE IS TIMELINES FROM A SPECIFIC TOPIC
        CATEGORY FOUR IS TIMELINES FROM A MOVIE
        CATEGORY FIVE IS TIMELINES FROM A TV SERIES
        CATEGORY SIX IS TIMELINES FROM MEMORY
        CATEGORY SEVEN IS TIMELINES FROM NONFICTION BOOKS
        CATEGORY EIGHT IS TIMELINES FROM FICTION BOOKS
        CATEGORY NINE IS TIMELINES FROM SPECIFIC GENRES
        CATEGORY TEN IS TIMELINES FROM SPECIFIC CATEGORIES
    END CATEGORY LIST:
END COMMAND:


CREATE CATEGORIES:
    NAME OF CATEGORY IS "SET1.OBJECTS":
        CATEGORY ONE IS OBJECTS FROM BOOKS
        CATEGORY TWO IS OBJECTS SEEN
        CATEGORY THREE IS OBJECTS IMAGINED
        CATEGORY FOUR IS OBJECTS FROM GAMES
        CATEGORY FIVE IS OBJECTS FROM DEVICES
        CATEGORY SIX IS OBJECTS FROM SPECIFIC GAMES
        CATEGORY SEVEN IS OBJECTS FROM SPECIFIC BOOKS
        CATEGORY EIGHT IS OBJECTS FROM SPECIFIC DEVICES
    END CATEGORY LIST:
END COMMAND:


CREATE CATEGORIES:
    NAME OF CATEGORY IS "SET1.DEVICES":
        CATEGORY ONE IS DEVICES THAT ARE IMAGINED
        CATEGORY TWO IS DEVICES THAT ARE CREATED
        CATEGORY THREE IS DEVICES THAT ARE SEEN
        CATEGORY FOUR IS DEVICES THAT ARE UNSEEN
        CATEGORY FIVE IS DEVICES THAT ARE READ FROM A BOOK
        CATEGORY SIX IS DEVICES THAT ARE SEEN FROM A TV SERIES
        CATEGORY SEVEN IS DEVICES THAT ARE SEEN FROM NONFICTION
        CATEGORY EIGHT IS DEVICES THAT ARE SEEN FROM FICTION
        CATEGORY NINE IS DEVICES THAT ARE NAMED
        CATEGORY NINE IS DEVICES THAT ARE UNNAMED
        CATEGORY TEN IS DEVICES THAT ARE NATURAL
        CATEGORY ELEVEN IS DEVICES THAT ARE ARTIFICIAL
    END CATEGORY LIST:
END COMMAND:


CREATE CATEGORIES:
    NAME OF CATEGORY IS "SET1.MEASUREMENTS":
        CATEGORY ONE IS MEASUREMENTS FROM LENGTHS OF TIME
        CATEGORY TWO IS MEASUREMENTS FROM DISTANCES
        CATEGORY THREE IS MEASUREMENTS FROM COMPUTER TERMINOLOGY
        CATEGORY FOUR IS MEASUREMENTS FROM SPECIFIC GENRES
        CATEGORY FIVE IS MEASUREMENTS FROM SPECIFIC GENRE CATEGORIES
        CATEGORY SIX IS MEASUREMENTS FROM SPECIFIC CATEGORIES
        CATEGORY SEVEN IS MEASUREMENTS FROM TIME
        CATEGORY EIGHT IS MEASUREMENTS FROM SPACE
        CATEGORY NINE IS MEASUREMENTS FROM SPATIAL
        CATEGORY TEN IS MEASUREMENTS FROM TEMPORAL
        CATEGORY ELEVEN IS MEASUREMENTS FROM PREVIOUS KNOWLEDGE
        CATEGORY TWELVE IS MEASUREMENTS FROM THE SEASONS
        CATEGORY THIRTEEN IS MEASUREMENTS FROM THE UNIVERSE
        CATEGORY FOURTEEN IS MEASUREMENTS FROM THE PLANETS
        CATEGORY FIFTEEN IS MEASUREMENTS FROM THE COSMOS
        CATEGORY SIXTEEN IS MEASUREMENTS FROM THE GALAXIES
        CATEGORY SEVENTEEN IS MEASUREMENTS FROM THE SUN
        CATEGORY EIGHTEEN IS MEASUREMENTS FROM THE MOON
        CATEGORY NINETEEN IS MEASUREMENTS FROM THE SOLAR SYSTEM
        CATEGORY TWENTY IS MEASUREMENTS FROM FICTION BOOKS
        CATEGORY TWENTYONE IS MEASUREMENTS FROM NONFICTION BOOKS
        CATEGORY TWENTYTWO IS MEASUREMENTS FROM ESTIMATE
        CATEGORY TWENTYTHREE IS MEASUREMENTS FROM GUESSING
        CATEGORY TWENTYFOUR IS MEASUREMENTS FROM PRECISE READINGS
        CATEGORY TWENTYFIVE IS MEASUREMENTS FROM PREVIOUS COMPUTATIONS
    END CATEGORY LIST:
END COMMAND:


   
CREATE GROUP OF INFORMATION:
    SET NAME FOR GROUP AS "SET1.PLACES.A.B":
    MEMORY CAN RECALL COLLECTED INFORMATION FROM THIS GROUP OF INFORMATION;
        PLACES SEEN PHYSICALLY CAN BE CAN BE COLLECTED BY MEMORY
        PLACES THAT ARE READ FROM A BOOK AND OR IMAGINED CAN BE COLLECTED BY MEMORY
        PLACES THAT ARE FROM "FICTION" CAN BE IMAGINED AGAIN AND COLLECTED BY MEMORY
        PLACES THAT HAVE BEEN "VISITED" CAN BE IMAGINED AGAIN AND COLLECTED BY MEMORY
        PLACES THAT ARE FROM "NONFICTION" CAN BE IMAGINED AGAIN AND COLLECTED BY MEMORY
        PLACES THAT ARE TALKED ABOUT IN A MOVIE CAN BE IMAGINED AGAIN AND COLLECTED BY MEMORY
    END CATEGORY LIST:
END COMMAND:


CREATE GROUP OF INFORMATION:
    SET NAME FOR GROUP AS "SET1.ERAS.A.B":
    MEMORY CAN RECALL COLLECTED INFORMATION FROM THIS GROUP OF INFORMATION;
        ERAS IN HISTORY CAN BE COLLECTED BY MEMORY
        ERAS IN A BOOK CAN BE COLLECTED BY MEMORY
        ERAS IN A MOVIE CAN BE COLLECTED BY MEMORY
        ERAS IN A GAME CAN BE COLLECTED BY MEMORY
    END CATEGORY LIST:
END COMMAND:


MEMORY CAN RECALL PAST INFORMATION
MEMORY CAN RECALL PAST FUTURE INFORMATION
MEMORY CAN RECALL PAST PRESENT INFORMATION
MEMORY CAN RECALL PAST PAST INFORMATION


FUTURE INFORMATION CAN BE ANALYZED
FUTURE PAST INFORMATION CAN BE ANALYZED
FUTURE PRESENT INFORMATION CAN BE ANALYZED
FUTURE FUTURE INFORMATION CAN BE ANALYZED


".GOV" IS A NETWORK EXTENSION THAT IS ACCESSIBLE FROM A GOVERNMENT
".ORG" IS A NETWORK EXTENSION THAT IS ACCESSIBLE FROM AN ORGANIZATION
".NET" IS A NETWORK EXTENSION THAT IS ACCESSIBLE OVER A NETWORK
".COM" IS A NETWORK EXTENSION THAT IS PUBLIC ACCESS FOR A COMMUNITY


PUBLIC NETWORKS ARE NETWORKS ABLE TO BE ACCESSED BY ANYONE
PRIVATE NETWORKS ARE NETWORKS ONLY ACCESSIBLE BY A SPECIFIC GROUP OF PEOPLE OR LIST OF PEOPLE
PERSONAL NETWORKS ARE NETWORKS THAT ARE MADE AS LOCAL NETWORKS FOR A SPECIFIC INDIVIDUAL OR SMALL GROUP OF PEOPLE
LOCAL NETWORKS ARE NETWORKS THAT ARE MADE AS NETWORKS WITHIN A SPECIFIC PLACE OR LOCATION THAT IS LOCAL


EACH PERSON THAT EXISTS HAS THEIR OWN MAGNETIC FIELD
EACH PERSON THAT EXISTS HAS THEIR OWN AURA FIELD
EACH PERSON THAT EXISTS HAS THEIR OWN CHAKRAS
EACH PERSON THAT EXISTS HAS THEIR OWN THOUGHT PROCESS
EACH PERSON THAT EXISTS HAS THEIR OWN PERSONALITY
EACH PERSON THAT EXISTS HAS THEIR OWN BRAINWAVES
EACH PERSON THAT EXISTS HAS THEIR OWN LEARNING METHOD


SOME LEARNING METHODS ARE SIMILAR WHILE OTHERS ARE DIFFERENT


EARTH HAS ITS OWN MAGNETIC FIELD
EARTH HAS ITS OWN GRAVITY


EACH PERSON THAT EXISTS HAS THE POTENTIAL TO RESONATE WITH THEIR INDIVIDUAL MAGNETIC FIELD
EACH PERSON THAT EXISTS HAS THE POTENTIAL TO LEARN SOMETHING NEW
EACH PERSON THAT EXISTS HAS THE POTENTIAL TO LEARN NEW SKILLS
EACH PERSON THAT EXISTS HAS THE POTENTIAL TO MASTER A SPECIFIC SET OF SKILLS AND OR ABILITIES
EACH PERSON THAT EXISTS HAS THE POTENTIAL TO LEARN MANY EXISTING LANGUAGES
EACH PERSON THAT EXISTS HAS THE POTENTIAL TO LEARN VAST AMOUNTS OF EQUATIONS AND FORMULAS USING THE MIND
EACH PERSON THAT EXISTS HAS THE POTENTIAL TO MASTER MANY FIELDS AND CATEGORIES
EACH PERSON THAT EXISTS HAS THE POTENTIAL TO MASTER MANY SPECIFIC FORMS OF KNOWLEDGE
EACH PERSON THAT EXISTS HAS THE POTENTIAL TO READ AND STORE INFORMATION IN MEMORY TO RECALL
EACH PERSON THAT EXISTS HAS THE POTENTIAL TO RECALL INFORMATION FROM A PREVIOUS EXPERIENCED EVENT OR MEMORY
EACH PERSON THAT EXISTS HAS THE POTENTIAL TO RECALL INFORMATION FROM AN IMAGE SEEN BEFORE AND OR OBJECT SEEN OR IMAGINED
EACH PERSON THAT EXISTS HAS THE POTENTIAL TO LEARN VAST AMOUNTS OF ALGORITHMS
EACH PERSON THAT EXISTS HAS THE POTENTIAL TO CREATE NEW SKILLS AND ABILITIES
EACH PERSON THAT EXISTS HAS THE POTENTIAL TO DEFINE NEW TERMS AND CUSTOM DEFINITIONS WITHIN THEIR OWN LANGUAGE
EACH PERSON THAT EXISTS HAS THE POTENTIAL TO DEVELOP THEIR OWN LANGUAGE
EACH PERSON THAT EXISTS HAS THE POTENTIAL TO CREATE NEW ABILITIES OF THEIR OWN
EACH PERSON THAT EXISTS HAS THE POTENTIAL TO CREATE NEW INFORMATION BY WRITING ON A PIECE OF PAPER OR TYPING OUT THE INFORMATION ON A KEYBOARD
EACH PERSON THAT EXISTS HAS THE POTENTIAL TO CREATE NEW OBJECTS AND TOOLS OF THEIR OWN
EACH PERSON THAT EXISTS HAS THE POTENTIAL TO CREATE NEW SKILLS AND TRAITS IN LIFE