from Language_Early_Stage import *
from Types_Of_Wavelengths import *
from Language_Extension_001 import *
from Types_Of_Dimension_Value import *
from Types_Of_Seasons import *
from Time_Of_Day import *
from Types_Of_Time import *
from Types_Of_Length import *
from Types_Of_Calendar_Time import *
CREATE,NEW,CLASS
NEW,CLASS,SHALL,BE,GIVEN,NAME,"FREQUENCY.CLASSES"
CLASS,SHALL,CONTAIN,THE,NAME,FOR,FIVE,DIFFERENT,TYPES,FOR,FREQUENCIES
TYPE,ONE,IS,AN,ALPHA,WAVELENGTH
TYPE,TWO,IS,AN,BETA,WAVELENGTH
TYPE,THREE,IS,AN,THETA,WAVELENGTH
TYPE,FOUR,IS,AN,DELTA,WAVELENGTH

CREATE,NEW,CLASS
NEW,CLASS,SHALL,BE,GIVEN,NAME,"WAVELENGTH.CLASSES"
CLASS,SHALL,CONTAIN,THE,DATA,USED,TO,GATHER,INFORMATION,FROM,WAVELENGTH,DATA
DATA,SHALL,BE,GATHERED,FROM,THE,BEGINNING,LOCATION,FOR,A,WAVELENGTH
DATA,SHALL,BE,GATHERED,FROM,THE,DESTINATION,LOCATION,FOR,A,WAVELENGTH
DATA,SHALL,BE,GATHERED,FROM,THE,FREQUENCY,INFORMATION,GATHERED,FROM,WITHIN,THE,WAVELENGTH
DATA,SHALL,BE,GATHERED,ON,THE,NUMBER,FOR,CYCLES,A,WAVELENGTH,HAS
DATA,SHALL,BE,GATHERED,ON,THE,HERTZ,FOR,A,WAVELENGTH
DATA,SHALL,BE,GATHERED,ON,THE,LENGTH,FOR,A,WAVELENGTH
DATA,SHALL,BE,GATHERED,ON,THE,HEIGHT,FOR,A,WAVELENGTH

CREATE,NEW,CLASS
NEW,CLASS,SHALL,BE,GIVEN,NAME,"UNIT.TYPES"
DATA,FORMED,FROM,UNIT,TYPES,HAVE,A,SPECIFIC,FORM,FOR,INFORMATION,THAT,HAS,THE,INFORMATION,FOR,THE,UNIT,SIZE,AND,UNIT,LEVEL,FOR,THAT,SPECIFIC,UNIT,TYPE
DATA,ANALYZED,AND,CONSIDERED,DATA,FOR,A,UNIT,TYPE,SHALL,HAVE,A,METHOD,FORMED,TO,CALCULATE,UNIT,SIZE
EACH,FORM,FOR,DATA,MEASURED,SHALL,HOLD,A,SPECIFIC,AMOUNT,FOR,DATA,TO,ANSWER,DATA,SIZE,LEVEL,AT,A,FUTURE,DATE

CREATE,NEW,COMMAND,PROMPT
SET,NEW,COMMAND,TO,GATHER,DATA,FROM,A,PARAMETER,WHEN,REQUEST,HAS,BEEN,MADE
EACH,FORM,FOR,DATA,SHALL,BE,GIVEN,A,CATEGORY,LOCATION,TO,FORM,OUTPUT,TO,GIVING,EACH,TYPE,FOR,DATA,A,LOCATION,TO,BE,STORED,WITH,A,CATEGORY,NAME

CREATE,CLASS,FOR,IF,STATEMENT,MANAGER,SETTINGS,FOR,MANAGING,FLOW,FOR,MEMORY,FOR,USED,IF,STATEMENT,FOR,PAST,RECALL
EACH,IF,STATEMENT,SHALL,BE,USED,TO,RECALL,PREVIOUS,FORMS,FOR,INFORMATION,WITHIN,DATA
IF,EACH,FORM,FOR,IF,STATEMENT,IS,ABLE,TO,GAIN,ACCESS,TO,A,PREVIOUS,TERM
CHECK,IF,STATEMENT,IS,A,FORM,FOR,COMMAND,AND,NOT,A,CATEGORY,REFERENCE
IF,STATEMENT,IS,A,CATEGORY,FOR,REFERENCE
THEN,DISPLAY,CATEGORY
ELSE,DISPLAY,PREVIOUS,TERM,ACCESSED

MAKE,OPTION,TO,ALLOW,RECALLING,WORDS,USED
MAKE,OPTION,TO,ALLOW,READING,A,DOCUMENT
MAKE,OPTION,TO,ALLOW,SCANNING,PARTICLE,DATA
MAKE,OPTION,TO,ALLOW,SCANNING,FREQUENCY,DATA
MAKE,OPTION,TO,MEASURE,A,DIMENSIONAL,LENGTH
MAKE,OPTION,TO,LEARN,DATA,GIVEN,TO,READ
MAKE,OPTION,TO,READ,EMOTIONAL,RESPONSES

A,WORD,IS,MADE,FROM,MORE,THAN,ONE,LETTER
A,BOOK,CONSISTS,OF,MORE,THAN,ONE,WORD
A,SCRIPT,CONSISTS,OF,MORE,THAN,ONE,WORD
A,LIBRARY,CAN,HOLD,MANY,FORMS,FOR,SPECIFIC,KNOWLEDGE

CREATE,OPTION,TO,FORM,PARAGRAPHS,WITH,WORDS
CREATE,OPTION,TO,FORM,A,PARAGRAPH,WITH,WORDS
CREATE,OPTION,TO,RECOGNIZE,DATA,CLASS
CREATE,OPTION,TO,RECALL,DATA,FROM,OTHER,DATA
CREATE,OPTION,TO,RECOGNIZE,A,EXTENSION,TYPE,FOR,FILE,DATA
CREATE,OPTION,TO,RECOGNIZE,FREQUENCY,DATA,FROM,PATTERN,RESPONSE,DATA

CREATE,CALIBRATION,SYSTEM,THAT,SHALL,BE,USED,TO,MEASURE,FREQUENCY,DATA
CREATE,MEASUREMENT,SYSTEM,THAT,SHALL,BE,USED,TO,MEASURE,DATA
CREATE,FREQUENCY,SYSTEM,THAT,SHALL,BE,USED,TO,GATHER,DATA,FROM,LEARNED,FREQUENCY,PATTERNS

RECALL,DATA,WITHIN,SYSTEM,INTERFACE,FOR,COLLECTED,COORDINATE,POINTS,TO,REFERENCE,DATA,FROM
PROCESSED,REFERENCE,DATA,SHALL,BE,USED,TO,GIVE,A,CALCULATE,DATA,BY,CATEGORY,DATA,BY,POSSIBILITY,AND,CHANCE,FOR,HAPPENING,THAN,METHOD,OR,STRUCTURED,DATA
RECALL,POSSIBILITY,AS,CAN,BE,DONE,IF,POSSIBILITY,EXISTS

MAKE,COORDINATE,PLANE
GIVE,VALUE,TO,PLANE,TO,HAVE,LENGTH,FOR,40,INCHES
GIVE,VALUE,TO,PLANE,TO,HAVE,WIDTH,FOR,40,INCHES

CREATE,NEW,WORD
WORD,SHALL,BE,GIVEN,NAME,AS,"UPSTAIRSWALKER"
WORD,DEFINITION,SHALL,BE,"_ENTERDEFINITIONHERE_"

POWER,FOR,LENGTH,[SETPOWERFORLENGTHHERE]
POWER,FOR,WIDTH,[SETPOWERFORWIDTHHERE]
POWER,FOR,HEIGHT,[SETPOWERFORWIDTHHERE]

IF,FILE,HAS,AN,EXTENSION
THEN,ANALYZE,TYPE,FOR,FILE,EXTENSION

IF,DATA,HAS,A,MEASUREMENT
THEN,DETERMINE,CHOICE,FOR,MEASUREMENT,CLASS
THEN,DETERMINE,CHOICE,FOR,MEASUREMENT,CLASS,FROM,CHOICES

IF,CHOICE,MEASUREMENT,IS,INCHES
print("THE CHOICE FOR MEASUREMENT IS INCHES")
IF,ELSE,THEN,DETERMINE,IF,MEASUREMENT,IS,CENTIMETERS
IF,CHOICE,MEASUREMENT,IS,CENTIMETERS
print("THE CHOICE FOR MEASUREMENT IS CENTIMETERS")

IF,POSSIBILITY,EXISTS,IN,MULTIPLE,FORMS,THEN,CHOOSE,THE,POSSIBILITY,WITH,BETTER,ACCURATE,EFFECTS,THAN,THE,NEUTRAL,OR,NEGATIVE,OUTCOME
MAKE,PROCESS,FOR,RECALL,PROCEDURE,TO,RECOGNIZE,COLLECTED,DATA,WITH,MANY,FORMS,FOR,TYPES,AND,CLASSES
EACH,POSSIBILITY,RECOGNIZED,MUST,BE,MADE,INTO,REFERENCE,DATA,FOR,RECALL,METHOD,TO,HAPPEN
WHEN,REFERENCE,DATA,IS,GATHERED,MAKE,POSSIBILITY,TO,GATHER,DATA,FROM,REFERENCE,SOURCE,RELATING,TO,POSITION,AND,POINT,FOR,ORIGIN,TO,OUTPUT,KNOWN,EFFECT

IF,SCANNER,WAS,NOT,ABLE,TO,FIND,RESULT,AT,THE,END,FOR,THE,SCANNING,PROCESS
THEN,END,SCANNING,PROCESS

IF,DATA,IS,RECOGNIZED,BY,A,CATEGORY
THEN,DISPLAY,CATEGORY,FOR,CATEGORY,IF,ASKED,FOR,CATEGORY

IF,THERE,IS,A,CLASS,WITHOUT,A,NAME
THEN,ALLOW,TO,REQUEST,FOR,A,NAME,FOR,THE,CLASS

IF,THERE,IS,A,CLASS,WITHOUT,A,TYPE
THEN,ALLOW,TO,REQUEST,FOR,A,TYPE,FOR,THE,CLASS

IF,THERE,IS,A,TYPE,WITHOUT,A,ELEMENT
THEN,ALLOW,TO,REQUEST,FOR,A,ELEMENT,FOR,THE,TYPE

IF,DATA,HAS,NO,CATEGORY
THEN,MAKE,CATEGORY,FOR,DATA,WITH,NAME,"UNKNOWN,CATEGORY"

CREATE,NEW,METHOD
METHOD,SHALL,BE,USED,TO,CALCULATE,LENGTH,OF,DIMENSION
CALCULATED,DATA,SHALL,BE,CALCULATED,WITH,NUMBER,VALUE

24,HOUR,VALUES,IS,EQUIVALENT,TO,1,DAY
60,MINUTE,VALUES,IS,EQUIVALENT,TO,1,HOUR
60,SECOND,VALUES,IS,EQUIVALENT,TO,1,MINUTE
1000,MILLISECOND,VALUES,IS,EQUIVALENT,TO,1,SECOND

1,MILLIMETER,VALUE,IS,EQUIVALENT,TO,1,MILLIMETER,VALUE
1,MILLIMETER,VALUE,IS,EQUIVALENT,TO,.1,CENTIMETER,VALUE
1,MILLIMETER,VALUE,IS,EQUIVALENT,TO,.001,METER,VALUE
1,MILLIMETER,VALUE,IS,EQUIVALENT,TO,.000001,KILOMETER,VALUE
1,MILLIMETER,VALUE,IS,EQUIVALENT,TO,.0393700787,INCHES,VALUE
1,MILLIMETER,VALUE,IS,EQUIVALENT,TO,.0032808399,FOOT,VALUE
1,MILLIMETER,VALUE,IS,EQUIVALENT,TO,.0010936133,YARD,VALUE
1,MILLIMETER,VALUE,IS,EQUIVALENT,TO,.00000062137119,MILE,VALUE

1,CENTIMETER,VALUE,IS,EQUIVALENT,TO,10,MILLIMETER,VALUE
1,CENTIMETER,VALUE,IS,EQUIVALENT,TO,1,CENTIMETER,VALUE
1,CENTIMETER,VALUE,IS,EQUIVALENT,TO,0.01,METER,VALUE
1,CENTIMETER,VALUE,IS,EQUIVALENT,TO,0.00001,KILOMETER,VALUE
1,CENTIMETER,VALUE,IS,EQUIVALENT,TO,0.3937007874,INCH,VALUE
1,CENTIMETER,VALUE,IS,EQUIVALENT,TO,0.032808399,FOOT,VALUE
1,CENTIMETER,VALUE,IS,EQUIVALENT,TO,0.010936133,YARD,VALUE
1,CENTIMETER,VALUE,IS,EQUIVALENT,TO,0.0000062137,MILE,VALUE

1,METER,VALUE,IS,EQUIVALENT,TO,1000,MILLIMETER,VALUES
1,METER,VALUE,IS,EQUIVALENT,TO,100,CENTIMETER,VALUES
1,METER,VALUE,IS,EQUIVALENT,TO,1,METER,VALUE
1,METER,VALUE,IS,EQUIVALENT,TO,0.001,KILOMETER,VALUE
1,METER,VALUE,IS,EQUIVALENT,TO,39.3700787402,INCH,VALUES
1,METER,VALUE,IS,EQUIVALENT,TO,3.280839895,FOOT,VALUES
1,METER,VALUE,IS,EQUIVALENT,TO,1.0936132983,YARD,VALUES
1,METER,VALUE,IS,EQUIVALENT,TO,0.0006213712,MILE,VALUE

1,KILOMETER,VALUE,IS,EQUIVALENT,TO,1000000,MILLIMETER,VALUES
1,KILOMETER,VALUE,IS,EQUIVALENT,TO,100000,CENTIMETER,VALUES
1,KILOMETER,VALUE,IS,EQUIVALENT,TO,1000,METER,VALUES
1,KILOMETER,VALUE,IS,EQUIVALENT,TO,1,KILOMETER,VALUE
1,KILOMETER,VALUE,IS,EQUIVALENT,TO,39370.078740157,INCH,VALUES
1,KILOMETER,VALUE,IS,EQUIVALENT,TO,3280.8398950131,FOOT,VALUES
1,KILOMETER,VALUE,IS,EQUIVALENT,TO,1093.6132983377,YARD,VALUE
1,KILOMETER,VALUE,IS,EQUIVALENT,TO,0.6213711922,MILE,VALUE

1,INCH,VALUE,IS,EQUIVALENT,TO,25.4,MILLIMETER,VALUES
1,INCH,VALUE,IS,EQUIVALENT,TO,2.54,CENTIMETER,VALUES
1,INCH,VALUE,IS,EQUIVALENT,TO,0.0254,METER,VALUE
1,INCH,VALUE,IS,EQUIVALENT,TO,0.0000254,KILOMETER,VALUE
1,INCH,VALUE,IS,EQUIVALENT,TO,1,INCH,VALUE
1,INCH,VALUE,IS,EQUIVALENT,TO,0.0833333333,FOOT,VALUE
1,INCH,VALUE,IS,EQUIVALENT,TO,0.0277777778,YARD,VALUE
1,INCH,VALUE,IS,EQUIVALENT,TO,0.0000157828,MILE,VALUE

1,FOOT,VALUE,IS,EQUIVALENT,TO,304.8,MILLIMETER,VALUES
1,FOOT,VALUE,IS,EQUIVALENT,TO,30.48,CENTIMETER,VALUES
1,FOOT,VALUE,IS,EQUIVALENT,TO,0.3048,METER,VALUE
1,FOOT,VALUE,IS,EQUIVALENT,TO,0.0003048,KILOMETER,VALUE
1,FOOT,VALUE,IS,EQUIVALENT,TO,12,INCH,VALUES
1,FOOT,VALUE,IS,EQUIVALENT,TO,1,FOOT,VALUES
1,FOOT,VALUE,IS,EQUIVALENT,TO,0.3333333333,YARD,VALUE
1,FOOT,VALUE,IS,EQUIVALENT,TO,0.0001893939,MILE,VALUE

1,YARD,VALUE,IS,EQUIVALENT,TO,914.4,MILLIMETER,VALUES
1,FOOT,VALUE,IS,EQUIVALENT,TO,91.44,CENTIMETER,VALUES
1,YARD,VALUE,IS,EQUIVALENT,TO,0.9144,METER,VALUE
1,YARD,VALUE,IS,EQUIVALENT,TO,914.4,MILLIMETER,VALUES
1,YARD,VALUE,IS,EQUIVALENT,TO,0.0009144,KILOMETER,VALUE
1,YARD,VALUE,IS,EQUIVALENT,TO,36,INCH,VALUES
1,YARD,VALUE,IS,EQUIVALENT,TO,3,FOOT,VALUES
1,YARD,VALUE,IS,EQUIVALENT,TO,1,YARD,VALUE
1,YARD,VALUE,IS,EQUIVALENT,TO,0.0005681818,MILE,VALUE

1,MILE,VALUE,IS,EQUIVALENT,TO,1609344,MILLIMETER,VALUES
1,MILE,VALUE,IS,EQUIVALENT,TO,160934.4,CENTIMETER,VALUES
1,MILE,VALUE,IS,EQUIVALENT,TO,1609.344,METER,VALUES
1,MILE,VALUE,IS,EQUIVALENT,TO,1.609344,KILOMETER,VALUES
1,MILE,VALUE,IS,EQUIVALENT,TO,63360,INCH,VALUES
1,MILE,VALUE,IS,EQUIVALENT,TO,5280,FOOT,VALUES
1,MILE,VALUE,IS,EQUIVALENT,TO,1760,YARD,VALUES
1,MILE,VALUE,IS,EQUIVALENT,TO,1,MILE,VALUE

#INCHES
AN,INCH,IS,A,MEASUREMENT
AN,INCH,IS,A,VALUE
AN,INCH,IS,DATA
AN,INCH,IS,INFORMATION

MEASURED,INCH,VALUES,CAN,CALCULATE,DISTANCE
INCH,VALUES,CAN,CALCULATE,DISTANCE
INCH,VALUES,CAN

AN,INCH,IS,CONSIDERED,A,TYPE,OF,TIME,MEASUREMENT
AN,INCH,IS,AN,TIME,MEASUREMENT

#CENTIMETERS
AN,CENTIMETER,IS,A,MEASUREMENT
AN,CENTIMETER,IS,A,VALUE
AN,CENTIMETER,IS,DATA
AN,CENTIMETER,IS,INFORMATION

MEASURED,CENTIMETER,VALUES,CAN,CALCULATE,DISTANCE
CENTIMETER,VALUES,CAN,CALCULATE,DISTANCE
CENTIMETER,VALUES,CAN

AN,CENTIMETER,IS,CONSIDERED,A,TYPE,OF,TIME,MEASUREMENT
AN,CENTIMETER,IS,AN,TIME,MEASUREMENT

#METERS
AN,METER,IS,A,MEASUREMENT
AN,METER,IS,A,VALUE
AN,METER,IS,DATA
AN,METER,IS,INFORMATION

MEASURED,METER,VALUES,CAN,CALCULATE,DISTANCE
METER,VALUES,CAN,CALCULATE,DISTANCE
METER,VALUES,CAN

AN,METER,IS,CONSIDERED,A,TYPE,OF,TIME,MEASUREMENT
AN,METER,IS,AN,TIME,MEASUREMENT

#KILOMETERS
AN,KILOMETER,IS,A,MEASUREMENT
AN,KILOMETER,IS,A,VALUE
AN,KILOMETER,IS,DATA
AN,KILOMETER,IS,INFORMATION

MEASURED,KILOMETER,VALUES,CAN,CALCULATE,DISTANCE
KILOMETER,VALUES,CAN,CALCULATE,DISTANCE
KILOMETER,VALUES,CAN

AN,KILOMETER,IS,CONSIDERED,A,TYPE,OF,TIME,MEASUREMENT
AN,KILOMETER,IS,AN,TIME,MEASUREMENT

#FEET
AN,FEET,IS,A,MEASUREMENT
AN,FEET,IS,A,VALUE
AN,FEET,IS,DATA
AN,FEET,IS,INFORMATION

MEASURED,FEET,VALUES,CAN,CALCULATE,DISTANCE
FEET,VALUES,CAN,CALCULATE,DISTANCE
FEET,VALUES,CAN

AN,FEET,IS,CONSIDERED,A,TYPE,OF,TIME,MEASUREMENT
AN,FEET,IS,AN,TIME,MEASUREMENT

#YARDS
AN,YARD,IS,A,MEASUREMENT
AN,YARD,IS,A,VALUE
AN,YARD,IS,DATA
AN,YARD,IS,INFORMATION

MEASURED,YARD,VALUES,CAN,CALCULATE,DISTANCE
YARD,VALUES,CAN,CALCULATE,DISTANCE
YARD,VALUES,CAN

AN,YARD,IS,CONSIDERED,A,TYPE,OF,TIME,MEASUREMENT
AN,YARD,IS,AN,TIME,MEASUREMENT

#MILES
AN,MILE,IS,A,MEASUREMENT
AN,MILE,IS,A,VALUE
AN,MILE,IS,DATA
AN,MILE,IS,INFORMATION

MEASURED,MILE,VALUES,CAN,CALCULATE,DISTANCE
MILE,VALUES,CAN,CALCULATE,DISTANCE
MILE,VALUES,CAN

AN,MILE,IS,CONSIDERED,A,TYPE,OF,TIME,MEASUREMENT
AN,MILE,IS,AN,TIME,MEASUREMENT
#---------------------------------------------------------
#SECONDS
AN,SECOND,IS,A,MEASUREMENT
AN,SECOND,IS,A,VALUE
AN,SECOND,IS,DATA
AN,SECOND,IS,INFORMATION

MEASURED,SECOND,VALUES,CAN,CALCULATE,DISTANCE
SECOND,VALUES,CAN,CALCULATE,DISTANCE
SECOND,VALUES,CAN

AN,SECOND,IS,CONSIDERED,A,TYPE,OF,TIME,MEASUREMENT
AN,SECOND,IS,AN,TIME,MEASUREMENT

#MILLISECONDS
AN,MILLISECOND,IS,A,MEASUREMENT
AN,MILLISECOND,IS,A,VALUE
AN,MILLISECOND,IS,DATA
AN,MILLISECOND,IS,INFORMATION

MEASURED,MILLISECOND,VALUES,CAN,CALCULATE,DISTANCE
MILLISECOND,VALUES,CAN,CALCULATE,DISTANCE
MILLISECOND,VALUES,CAN

AN,MILLISECOND,IS,CONSIDERED,A,TYPE,OF,TIME,MEASUREMENT
AN,MILLISECOND,IS,AN,TIME,MEASUREMENT

#MINUTES
AN,MINUTE,IS,A,MEASUREMENT
AN,MINUTE,IS,A,VALUE
AN,MINUTE,IS,DATA
AN,MINUTE,IS,INFORMATION

MEASURED,MINUTE,VALUES,CAN,CALCULATE,DISTANCE
MINUTE,VALUES,CAN,CALCULATE,DISTANCE
MINUTE,VALUES,CAN

AN,MINUTE,IS,CONSIDERED,A,TYPE,OF,TIME,MEASUREMENT
AN,MINUTE,IS,AN,TIME,MEASUREMENT

#HOURS
AN,HOUR,IS,A,MEASUREMENT
AN,HOUR,IS,A,VALUE
AN,HOUR,IS,DATA
AN,HOUR,IS,INFORMATION

MEASURED,HOUR,VALUES,CAN,CALCULATE,DISTANCE
HOUR,VALUES,CAN,CALCULATE,DISTANCE
HOUR,VALUES,CAN

AN,HOUR,IS,CONSIDERED,A,TYPE,OF,TIME,MEASUREMENT
AN,HOUR,IS,AN,TIME,MEASUREMENT

print(CREATE,NEW,CLASS)
print(NEW,CLASS,SHALL,BE,GIVEN,NAME,"FREQUENCY.CLASSES")
