from Language_Early_Stage import *
from Types_Of_Wavelengths import *
from Language_Extension_001 import *
from Types_Of_Dimension_Value import *
from Types_Of_Seasons import *
from Time_Of_Day import *
from Types_Of_Time import *
from Types_Of_Length import *
from Types_Of_Calendar_Time import *
from Numbers_One_To_OneThousand import *
#DEFAULT PROGRAM USED TO USE AN ['__EXTENSIONTYPE__'] FILE IS "__PROGRAMNAME__"
DEFAULT PROGRAM USED TO USE AN ['.MP4'] FILE IS "VLC_PLAYER"
DEFAULT PROGRAM USED TO USE AN ['.TXT'] FILE IS "NOTEPADPLUSPLUS"
DEFAULT PROGRAM USED TO USE AN ['.DOCX'] FILE IS "MICROSFORT_WORD"
DEFAULT PROGRAM USED TO USE AN ['.MP3'] FILE IS "VLC_PLAYER"
DEFAULT PROGRAM USED TO USE AN ['.PY'] FILE IS "VS_CODE"
DEFAULT PROGRAM USED TO USE AN ['.JSON'] FILE IS "VS_CODE"
 
#['__EXTENSIONTYPE__'] IS A FILE EXTENSION:
['.MP4'] IS A FILE EXTENSION
['.TXT'] IS A FILE EXTENSION
['.DOCX'] IS A FILE EXTENSION
['.MP3'] IS A FILE EXTENSION
['.PY'] IS A FILE EXTENSION
['.JSON'] IS A FILE EXTENSION
['.LNK'] IS A FILE EXTENSION
['.EXE'] IS A FILE EXTENSION
 
#("__FOLDER_PATH__") IS A FOLDER LOCATION:
("C:\ASUNAAI") IS A FOLDER LOCATION
("C:\ASUNAAI\EXTENSIONS") IS A FOLDER LOCATION

#("__FOLDER_PATH__") IS A FOLDER DIRECTORY:
("C:\ASUNAAI") IS A FOLDER DIRECTORY
("C:\ASUNAAI\EXTENSIONS") IS A FOLDER DIRECTORY
 
#("__FOLDER_PATH__") IS A FOLDER PATH:
("C:\ASUNAAI") IS A FOLDER PATH
("C:\ASUNAAI\EXTENSIONS") IS A FOLDER PATH
 
#["__FILENAME__"] IS A FILE:
["MPBR_Frequency"] IS A FILE
["Language_Early_Stage"] IS A FILE
 
#["__FILENAME__"] IS A ['__EXTENSIONTYPE__'] FILE:
["MPBR_Frequency"] IS A ['.TXT'] FILE
["Language_Early_Stage"] IS A ['.PY'] FILE
 
["__FILENAME__"] IS LOCATED WITHIN ("__FOLDER_PATH__"):
#["MPBR_Frequency"] IS LOCATED WITHIN ("C:\ASUNAAI\EXTENSIONS\TXT")
#["Language_Early_Stage"] IS LOCATED WITHIN ("C:\ASUNAAI\EXTENSIONS\PY")
 
LOCATE FILE WITH NAME ["__FILENAME__"] WITHIN FOLDER DIRECTORY ("__FOLDER_PATH__");
#LOCATE FILE WITH NAME ["MPBR_Frequency"] WITHIN FOLDER DIRECTORY ("C:\ASUNAAI\EXTENSIONS\TXT")
 
SCAN FOLDER DIRECTORY ("__FOLDER_PATH__") FOR FILE WITH NAME ["__FILENAME__"];
#SCAN FOLDER DIRECTORY ("C:\ASUNAAI\EXTENSIONS\PY") FOR FILE WITH NAME ["Language_Early_Stage"]
 
ANALYZE FOLDER DIRECTORY ("__FOLDER_PATH__") FOR ["__FILENAME__"];
#ANALYZE FOLDER DIRECTORY ("C:\ASUNAAI\EXTENSIONS\TXT") FOR ["MPBR_Frequency"]
 
CHANGE FOLDER DIRECTORY TO ("__FOLDER_PATH__");
#CHANGE FOLDER DIRECTORY TO ("C:\ASUNAAI\EXTENSIONS\MP3")
 
LIST ALL FOLDER LOCATIONS WITHIN ("__FOLDER_PATH__");
#LIST ALL FOLDER LOCATIONS WITHIN ("C:\ASUNAAI\EXTENSIONS\PY")
 
 
SCAN SYSTEM AND LOCATE FILE WITH NAME ["__FILENAME__"] AND OUTPUT FOLDER DIRECTORY
#SCAN SYSTEM AND LOCATE FILE WITH NAME ("MPBR_FREQUENCY.TXT") AND OUTPUT FOLDER DIRECTORY
 
SCAN SYSTEM AND LOCATE FOLDER WITH NAME ("__FOLDER_NAME__") AND OUTPUT DIRECTORY LOCATION
#SCAN SYSTEM AND LOCATE FOLDER WITH NAME ("EXTENSIONS") AND OUTPUT DIRECTORY LOCATION
 
SCAN FOR AND GO TO DIRECTORY ("__FOLDER_PATH__")
#SCAN FOR AND GO TO DIRECTORY ("C:/ASUNAAI/ASUNAAIEXTENSIONS/DOCX")
 
OPEN ["__FILENAME__"] WITHIN FILE DIRECTORY ("__FOLDER_PATH__")
#OPEN ["EDGELOREDOCUMENTS.DOCX"] WITHIN FILE DIRECTORY ("C:/ASUNAAI/ASUNAAIEXTENSIONS/DOCX")
 
OPEN ["__FILENAME__"] WITHIN FILE DIRECTORY ("__FOLDER_PATH__")
#OPEN "CHROME.LNK" WITHIN FILE DIRECTORY ("C:/ASUNAAI/ASUNAAIEXTENSIONS/LNK")
 
START ["__FILENAME__"] WITHIN FILE DIRECTORY ("__FOLDER_PATH__")
#START ["VLC_PLAYER.LNK"] WITHIN FILE DIRECTORY ("C:/ASUNAAI/ASUNAAIEXTENSIONS/LNK")
 
LOCATE FILE WITH NAME ["__FILENAME__"] WITHIN FILE DIRECTORY ("__FOLDER_PATH__") AND OPEN ["__FILENAME__"]
#LOCATE FILE WITH NAME ["EDGELOREDOCUMENTS.DOCX"] WITHIN FILE DIRECTORY ("C:/ASUNAAI") AND OPEN ["EDGELOREDOCUMENTS.DOCX"]
 
CREATE NEW FILE INSIDE FOLDER DIRECTORY ("__FOLDER_PATH__") AND NAME THE FILE ["__FILENAME__"]
#CREATE NEW FILE INSIDE FOLDER DIRECTORY ("C:/ASUNAAI/ASUNAAIEXTENSIONS/TXT") AND NAME THE FILE ["HELLO WORLD.TXT"]
 
CREATE NEW FOLDER INSIDE FOLDER DIRECTORY ("__FOLDER_PATH__") WITH NAME FOR FILE GIVEN ["__FILENAME__"]
#CREATE NEW FOLDER INSIDE FOLDER DIRECTORY ("C:/ASUNAAI/ASUNAAIEXTENSIONS") WITH NAME FOR FILE GIVEN "SEVENZIP"
 
GO TO FILE DIRECTORY ("__FOLDER_PATH__")
#GO TO FILE DIRECTORY ("C:/ASUNAAI/ASUNAAIEXTENSIONS")
 
LOCATE ALL FILES WITHIN FOLDER DIRECTORY ("__FOLDER_PATH__") WITH NAME ["__FILENAME__"]
#LOCATE ALL FILES WITHIN FOLDER DIRECTORY ("C:/ASUNAAI/") WITH NAME ["EDGELOREDOCUMENTS"]
 
CHANGE FILE DIRECTORY TO LOCATION ("__FOLDER_PATH__")
#CHANGE FILE DIRECTORY TO LOCATION ("C:/ASUNAAI/ASUNAAIEXTENSIONS")
 
ACTIVATE ["__FILENAME__"]
#ACTIVATE "VSCODE.LNK"