from Language_Early_Stage import *
from Types_Of_Wavelengths import *
from Language_Extension_001 import *
from Types_Of_Dimension_Value import *
from Types_Of_Seasons import *
from Time_Of_Day import *
from Types_Of_Time import *
from Types_Of_Length import *
from Types_Of_Calendar_Time import *
from Numbers_One_To_OneThousand import *
from Creature_Stats import *
from CreatureConditions import * 
from Pokemonarrayscript import *
CREATE,CATEGORIES;'/n'
'/t',NAME,OF,CATEGORY,IS,"SET1";
'/t/t',CATEGORY,ONE,IS,"PLACES"
'/t/t',CATEGORY,TWO,IS,"ERAS"
'/t/t',CATEGORY,THREE,IS,"PEOPLE"
'/t/t',CATEGORY,FIVE,IS,"TIMELINES"
'/t/t',CATEGORY,SIX,IS,"MEASUREMENTS"
'/t/t',CATEGORY,SEVEN,IS,"OBJECTS"
'/t/t',CATEGORY,EIGHT,IS,"DEVICES"
'/t/t',CATEGORY,NINE,IS,"VARIABLES"
'/t',END,CATEGORY,LIST;
END,COMMAND;

CREATE,CATEGORIES;'/n'
'/t',NAME,OF,CATEGORY,IS,"SET1.PLACES";
'/t/t',CATEGORY,ONE,IS,PLACES,VISITED
'/t/t',CATEGORY,TWO,IS,PLACES,READ,FROM,A,BOOK
'/t/t',CATEGORY,THREE,IS,PLACES,FROM,FICTION
'/t/t',CATEGORY,FOUR,IS,PLACES,FROM,NONFICTION
'/t/t',CATEGORY,FIVE,IS,PLACES,IMAGINED
'/t/t',CATEGORY,SIX,IS,PLACES,SEEN,PHYSICALLY
'/t',END,CATEGORY,LIST;
END,COMMAND;

CREATE,CATEGORIES;'/n'
'/t',NAME,OF,CATEGORY,IS,"SET1.ERAS";
'/t/t',CATEGORY,ONE,IS,ERAS,IN,HISTORY
'/t/t',CATEGORY,TWO,IS,ERAS,IN,A,BOOK
'/t',END,CATEGORY,LIST;
END,COMMAND;

CREATE,CATEGORIES;'/n'
'/t',NAME,OF,CATEGORY,IS,"SET1.PEOPLE";
'/t/t',CATEGORY,ONE,IS,PEOPLE,MET
'/t/t',CATEGORY,TWO,IS,PEOPLE,NOT,MET
'/t/t',CATEGORY,THREE,IS,PEOPLE,FROM,A,BOOK
'/t/t',CATEGORY,FOUR,IS,PEOPLE,FROM,NONFICTION
'/t/t',CATEGORY,FIVE,IS,PEOPLE,FROM,FICTION
'/t/t',CATEGORY,TEN,IS,PEOPLE,MET,OVER,A,NETWORK
'/t',END,CATEGORY,LIST;
END,COMMAND;

CREATE,CATEGORIES;'/n'
'/t',NAME,OF,CATEGORY,IS,"SET1.TIMELINES";
'/t/t',CATEGORY,ONE,IS,TIMELINES,IN,LIFE
'/t/t',CATEGORY,TWO,IS,TIMELINES,IN,A,SPECIFIC,BOOK
'/t/t',CATEGORY,THREE,IS,TIMELINES,FROM,A,SPECIFIC,TOPIC
'/t/t',CATEGORY,SIX,IS,TIMELINES,FROM,MEMORY
'/t/t',CATEGORY,SEVEN,IS,TIMELINES,FROM,NONFICTION,BOOKS
'/t/t',CATEGORY,EIGHT,IS,TIMELINES,FROM,FICTION,BOOKS
'/t/t',CATEGORY,NINE,IS,TIMELINES,FROM,SPECIFIC,GENRES
'/t/t',CATEGORY,TEN,IS,TIMELINES,FROM,SPECIFIC,CATEGORIES
'/t',END,CATEGORY,LIST;
END,COMMAND;

CREATE,CATEGORIES;'/n'
'/t',NAME,OF,CATEGORY,IS,"SET1.OBJECTS";
'/t/t',CATEGORY,ONE,IS,OBJECTS,FROM,BOOKS
'/t/t',CATEGORY,TWO,IS,OBJECTS,SEEN
'/t/t',CATEGORY,THREE,IS,OBJECTS,IMAGINED
'/t/t',CATEGORY,FIVE,IS,OBJECTS,FROM,DEVICES
'/t/t',CATEGORY,SEVEN,IS,OBJECTS,FROM,SPECIFIC,BOOKS
'/t/t',CATEGORY,EIGHT,IS,OBJECTS,FROM,SPECIFIC,DEVICES
'/t',END,CATEGORY,LIST;
END,COMMAND;

CREATE,CATEGORIES;'/n'
'/t',NAME,OF,CATEGORY,IS,"SET1.DEVICES";
'/t/t',CATEGORY,ONE,IS,DEVICES,THAT,ARE,IMAGINED
'/t/t',CATEGORY,TWO,IS,DEVICES,THAT,ARE,CREATED
'/t/t',CATEGORY,THREE,IS,DEVICES,THAT,ARE,SEEN
'/t/t',CATEGORY,FIVE,IS,DEVICES,THAT,ARE,READ,FROM,A,BOOK
'/t/t',CATEGORY,SEVEN,IS,DEVICES,THAT,ARE,READ,FROM,NONFICTION
'/t/t',CATEGORY,EIGHT,IS,DEVICES,THAT,ARE,READ,FROM,FICTION
'/t/t',CATEGORY,NINE,IS,DEVICES,THAT,ARE,NAMED
'/t/t',CATEGORY,TEN,IS,DEVICES,THAT,ARE,NATURAL
'/t/t',CATEGORY,ELEVEN,IS,DEVICES,THAT,ARE,ARTIFICIAL
'/t',END,CATEGORY,LIST;
END,COMMAND;

CREATE,CATEGORIES;'/n'
'/t',NAME,OF,CATEGORY,IS,"SET1.MEASUREMENTS";
'/t/t',CATEGORY,ONE,IS,MEASUREMENTS,FROM,MEASUREMENTS,OF,TIME
'/t/t',CATEGORY,FOUR,IS,MEASUREMENTS,FROM,SPECIFIC,GENRES
'/t/t',CATEGORY,FIVE,IS,MEASUREMENTS,FROM,SPECIFIC,GENRE,CATEGORIES
'/t/t',CATEGORY,SIX,IS,MEASUREMENTS,FROM,SPECIFIC,CATEGORIES
'/t/t',CATEGORY,SEVEN,IS,MEASUREMENTS,FROM,TIME
'/t/t',CATEGORY,EIGHT,IS,MEASUREMENTS,FROM,SPACE
'/t/t',CATEGORY,NINE,IS,MEASUREMENTS,FROM,SPATIAL
'/t/t',CATEGORY,TEN,IS,MEASUREMENTS,FROM,TEMPORAL
'/t/t',CATEGORY,ELEVEN,IS,MEASUREMENTS,FROM,PREVIOUS,KNOWLEDGE2
'/t/t',CATEGORY,TWENTY,IS,MEASUREMENTS,FROM,FICTION,BOOKS
'/t/t',CATEGORY,TWENTYONE,IS,MEASUREMENTS,FROM,NONFICTION,BOOKS
'/t',END,CATEGORY,LIST;
END,COMMAND;