from Language_Early_Stage import *
from Types_Of_Wavelengths import *
from Language_Extension_001 import *
from Types_Of_Dimension_Value import *
from Types_Of_Seasons import *
from Time_Of_Day import *
from Types_Of_Time import *
from Types_Of_Length import *
from Types_Of_Calendar_Time import *
from Numbers_One_To_OneThousand import *
from Creature_Stats import *
from CreatureConditions import * 
from Pokemonarrayscript import *
CREATE,NEW,CLASS;'/n'
'/t',NEW,CLASS,SHALL,BE,GIVEN,NAME,"WAVELENGTH.CLASSES";
'/t/t',CLASS,SHALL,CONTAIN,THE,DATA,USED,TO,GATHER,INFORMATION,FROM,WAVELENGTH,DATA
'/t/t/t',DATA,SHALL,BE,GATHERED,FROM,THE,BEGINNING,LOCATION,FOR,A,WAVELENGTH
'/t/t/t',DATA,SHALL,BE,GATHERED,FROM,THE,DESTINATION,LOCATION,FOR,A,WAVELENGTH
'/t/t/t',DATA,SHALL,BE,GATHERED,FROM,THE,FREQUENCY,INFORMATION,GATHERED,FROM,WITHIN,THE,WAVELENGTH
'/t/t/t',DATA,SHALL,BE,GATHERED,ON,THE,NUMBER,FOR,CYCLES,A,WAVELENGTH,HAS
'/t/t/t',DATA,SHALL,BE,GATHERED,ON,THE,HERTZ,FOR,A,WAVELENGTH
'/t/t/t',DATA,SHALL,BE,GATHERED,ON,THE,LENGTH,FOR,A,WAVELENGTH
'/t/t/t',DATA,SHALL,BE,GATHERED,ON,THE,HEIGHT,FOR,A,WAVELENGTH
'/t/t',END,CLASS;
'/t',END,CLASS,NAMING;
END,CREATE,NEW,CLASS;

CREATE,NEW,CLASS;'/n'
'/t',NEW,CLASS,SHALL,BE,GIVEN,NAME,"UNIT.TYPES";
'/t/t',DATA,FORMED,FROM,UNIT,TYPES,HAVE,A,SPECIFIC,FORM,FOR,INFORMATION,THAT,HAS,THE,INFORMATION,FOR,THE,UNIT,SIZE,AND,UNIT,LEVEL,FOR,THAT,SPECIFIC,UNIT,TYPE
'/t/t',DATA,ANALYZED,AND,CONSIDERED,DATA,FOR,A,UNIT,TYPE,SHALL,HAVE,A,METHOD,FORMED,TO,CALCULATE,UNIT,SIZE
'/t/t/t',EACH,FORM,FOR,DATA,MEASURED,SHALL,HOLD,A,SPECIFIC,AMOUNT,FOR,DATA,TO,ANSWER,DATA,SIZE,LEVEL,AT,A,FUTURE,DATE
'/t/t',END,COMMANDS;
'/t',END,CLASS,NAMING;
END,CLASS;

CREATE,NEW,COMMAND,PROMPT;'/n'
'/t',SET,NEW,COMMAND,TO,GATHER,DATA,FROM,A,PARAMETER,WHEN,REQUEST,HAS,BEEN,MADE
'/t/t',EACH,FORM,FOR,DATA,SHALL,BE,GIVEN,A,CATEGORY,LOCATION,TO,FORM,OUTPUT,TO,GIVING,EACH,TYPE,FOR,DATA,A,LOCATION,TO,BE,STORED,WITH,A,CATEGORY,NAME
'/t',END,COMMAND,PROMPT;
END,COMMAND;

IF,DATA,GIVEN,A,CATEGORY,DOES,NOT,MATCH,DATA,WITH,CATEGORY;'/n'
'/t',THEN,SCAN,OTHER,CATEGORIES,EXISTING,AND,CALCULATE,CATEGORY,WITH,SIMILAR,MATCH,TO,DATA,WITHIN,CATEGORY
'/t',END,IF,STATEMENT;

IF,FILE,HAS,AN,EXTENSION;'/n'
'/t',THEN,ANALYZE,TYPE,FOR,FILE,EXTENSION
'/t',END,IF,STATEMENT;


IF,DATA,HAS,A,MEASUREMENT;'/n'
'/t',THEN,DETERMINE,CHOICE,FOR,MEASUREMENT,CLASS;
'/t/t',THEN,DETERMINE,CHOICE,FOR,MEASUREMENT,CLASS,FROM,CHOICES
'/t/t',IF,CHOICE,MEASUREMENT,IS,INCHES
'/t/t/t',print("THE CHOICE FOR MEASUREMENT IS INCHES")
'/t/t',IF,ELSE,THEN,DETERMINE,IF,MEASUREMENT,IS,CENTIMETERS
'/t/t',IF,CHOICE,MEASUREMENT,IS,CENTIMETERS
'/t/t/t',print("THE CHOICE FOR MEASUREMENT IS CENTIMETERS")
'/t/t',END,IF,STATEMENTS;
'/t',END,COMMAND;
END,IF,STATEMENT;

CREATE,CLASS,FOR,IF,STATEMENT,MANAGER,SETTINGS,FOR,MANAGING,FLOW,FOR,MEMORY,FOR,USED,IF,STATEMENT,FOR,PAST,RECALL;'/n'
'/t',EACH,IF,STATEMENT,SHALL,BE,USED,TO,RECALL,PREVIOUS,FORMS,FOR,INFORMATION,WITHIN,DATA
'/t',IF,EACH,FORM,FOR,IF,STATEMENT,IS,ABLE,TO,GAIN,ACCESS,TO,A,PREVIOUS,TERM
'/t/t',CHECK,IF,STATEMENT,IS,A,FORM,FOR,COMMAND,AND,NOT,A,CATEGORY,REFERENCE
'/t/t',IF,STATEMENT,IS,A,CATEGORY,FOR,REFERENCE
'/t/t/t',THEN,DISPLAY,CATEGORY
'/t/t/t',ELSE,DISPLAY,PREVIOUS,TERM,ACCESSED
'/t/t',END,IF,STATEMENT;
'/t',END,IF,STATEMENT;
END,COMMAND;
