from Language_Early_Stage import *
from Types_Of_Wavelengths import *
from Language_Extension_001 import *
from Types_Of_Dimension_Value import *
from Types_Of_Seasons import *
from Time_Of_Day import *
from Types_Of_Time import *
from Types_Of_Length import *
from Types_Of_Calendar_Time import *
from Numbers_One_To_OneThousand import *
from Creature_Stats import *
from CreatureConditions import * 
from Pokemonarrayscript import *
CREATE,NEW,CLASS;'/n'
'/t',NEW,CLASS,SHALL,BE,GIVEN,NAME,"STATES_OF_CONSCIOUSNESS.CLASSES";
'/t/t',CLASS,SHALL,CONTAIN,THE,NAME,FOR,FIVE,DIFFERENT,TYPES,FOR,THE,EXISTING,STATES,OF,CONSCIOUSNESS
'/t/t',TYPE,ONE,IS,THE,"CONSCIOUSNESS"
'/t/t',TYPE,TWO,IS,THE,"UNCONSCIOUSNESS"
'/t/t',TYPE,THREE,IS,THE,"NONCONSCIOUSNESS"
'/t/t',TYPE,FOUR,IS,THE,"SUBCONCSCIOUSNESS"
'/t/t',TYPE,FIVE,IS,THE,"SUPERCONSCIOUSNESS"
'/t',END,CLASS;
END,COMMAND;

CREATE,NEW,CLASS;'/n'
'/t',NEW,CLASS,SHALL,BE,GIVEN,NAME,"EYESIGHT.CLASSES";
'/t/t',CLASS,SHALL,CONTAIN,THE,NAME,FOR,TWO,DIFFERENT,TYPES,FOR,EYESIGHT
'/t/t',TYPE,ONE,IS,AN,"NEAR-SIGHTED",EYESIGHT
'/t/t',TYPE,TWO,IS,AN,"FAR-SIGHTED",EYESIGHT
'/t',END,CLASS;
END,COMMAND;

CREATE,NEW,CLASS;'/n'
'/t',NEW,CLASS,SHALL,BE,GIVEN,NAME,"MEMORY.CLASSES";
'/t/t',CLASS,SHALL,CONTAIN,THE,NAME,FOR,TWO,DIFFERENT,TYPES,FOR,MEMORY
'/t/t',TYPE,ONE,IS,"LONG-TERM",MEMORY
'/t/t',TYPE,TWO,IS,"SHORT-TERM",MEMORY
'/t',END,CLASS;
END,COMMAND;

CREATE,NEW,CLASS;'/n'
'/t',NEW,CLASS,SHALL,BE,GIVEN,NAME,"AUTOMATION.CLASSES";
'/t/t',CLASS,SHALL,CONTAIN,THE,NAME,FOR,FOUR,DIFFERENT,TYPES,FOR,"AUTOMATION"
'/t/t',TYPE,ONE,IS,"AUTOMATIC"
'/t/t',TYPE,TWO,IS,"SEMI-AUTOMATIC"
'/t/t',TYPE,THREE,IS,"SEMI-MANUAL"
'/t/t',TYPE,FOUR,IS,"MANUAL"
'/t',END,CLASS;
END,COMMAND;

CREATE,NEW,CLASS;'/n'
'/t',NEW,CLASS,SHALL,BE,GIVEN,NAME,"MOON_PHASE.CLASSES";
'/t/t',CLASS,SHALL,CONTAIN,THE,NAME,FOR,FIVE,DIFFERENT,TYPES,FOR,FREQUENCIES
'/t/t',TYPE,ONE,IS,THE,"NEW,MOON"
'/t/t',TYPE,TWO,IS,THE,"CRESENT,MOON"
'/t/t',TYPE,THREE,IS,THE,"WAXING,QUARTER,MOON"
'/t/t',TYPE,FOUR,IS,THE,"GIBBOUS,MOON"
'/t/t',TYPE,FIVE,IS,THE,"FULL,MOON"
'/t',END,CLASS;
END,COMMAND;

CREATE,NEW,CLASS;'/n'
'/t',NEW,CLASS,SHALL,BE,GIVEN,NAME,"FREQUENCY.CLASSES";
'/t/t',CLASS,SHALL,CONTAIN,THE,NAME,FOR,FIVE,DIFFERENT,TYPES,FOR,FREQUENCIES
'/t/t',TYPE,ONE,IS,AN,"ALPHA",WAVELENGTH
'/t/t',TYPE,TWO,IS,AN,"BETA",WAVELENGTH
'/t/t',TYPE,THREE,IS,AN,"THETA",WAVELENGTH
'/t/t',TYPE,FOUR,IS,AN,"DELTA",WAVELENGTH
'/t/t',TYPE,FIVE,IS,AN,"GAMMA",WAVELENGTH
'/t',END,CLASS;
END,COMMAND;

CREATE,NEW,CLASS;'/n'
'/t',NEW,CLASS,SHALL,BE,GIVEN,NAME,"INTELLIGENCE.CLASSES";
'/t/t',CLASS,SHALL,CONTAIN,THE,NAME,FOR,EIGHT,DIFFERENT,TYPES,OF,INTELLIGENCE2
'/t/t',TYPE,ONE,IS,"VERBAL LINGUISTIC INTELLIGENCE"
'/t/t',TYPE,TWO,IS,"LOGICAL MATHEMATICAL INTELLIGENCE"
'/t/t',TYPE,THREE,IS,"SPATIAL INTELLIGENCE"
'/t/t',TYPE,FOUR,IS,"MUSICAL INTELLIGENCE"
'/t/t',TYPE,FIVE,IS,"BODILY KINAESTHETIC INTELLIGENCE"
'/t/t',TYPE,SIX,IS,"INTERPERSONAL INTELLIGENCE"
'/t/t',TYPE,SEVEN,IS,"INTRAPERSONAL INTELLIGENCE"
'/t/t',TYPE,EIGHT,IS,"NATURALISTIC INTELLIGENCE"
'/t',END,CLASS;
END,COMMAND;

CREATE,NEW,CLASS;'/n'
'/t',NEW,CLASS,SHALL,BE,GIVEN,NAME,"BRAIN.CLASSES";
'/t/t',CLASS,SHALL,CONTAIN,THE,NAME,FOR,SIX,DIFFERENT,TYPES,OF,"BRAIN CLASSES"
'/t/t',TYPE,ONE,IS,THE,"FRONTAL LOBE"
'/t/t',TYPE,TWO,IS,THE,"TEMPORAL LOBE"
'/t/t',TYPE,THREE,IS,THE,"PARIETAL LOBE"
'/t/t',TYPE,FOUR,IS,THE,"OCCIPITAL LOBE"
'/t/t',TYPE,FIVE,IS,THE,"CEREBELLUM"
'/t/t',TYPE,SIX,IS,THE,"BRAIN STEM"
'/t',END,CLASS;
END,COMMAND;

CREATE,NEW,CLASS;'/n'
'/t',NEW,CLASS,SHALL,BE,GIVEN,NAME,"CHAKRA.CLASSES";
'/t/t',CLASS,SHALL,CONTAIN,THE,NAME,FOR,SEVEN,DIFFERENT,TYPES,CHAKRA
'/t/t',TYPE,ONE,IS,THE,"CROWN,CHAKRA"
'/t/t',TYPE,TWO,IS,THE,"THIRD,EYE,CHAKRA"
'/t/t',TYPE,THREE,IS,THE,"THROAT,CHAKRA"
'/t/t',TYPE,FOUR,IS,THE,"HEART,CHAKRA"
'/t/t',TYPE,FIVE,IS,THE,"SOLAR,PLEXUS,CHAKRA"
'/t/t',TYPE,FIVE,IS,THE,"SACRAL,CHAKRA"
'/t/t',TYPE,FIVE,IS,THE,"ROOT,CHAKRA"
'/t',END,CLASS;
END,COMMAND;

CREATE,NEW,CLASS;'/n'
'/t',NEW,CLASS,SHALL,BE,GIVEN,NAME,"AURA.CLASSES";
'/t/t',CLASS,SHALL,CONTAIN,THE,NAME,FOR,SEVEN,DIFFERENT,TYPES,FOR,AURA
'/t/t',TYPE,ONE,IS,THE,"CAUSAL,BODY"
'/t/t',TYPE,TWO,IS,THE,"CELESTIAL,AURA"
'/t/t',TYPE,THREE,IS,THE,"ETHERIC,TEMPLATE"
'/t/t',TYPE,FOUR,IS,THE,"ASTRAL,AURA"
'/t/t',TYPE,FIVE,IS,THE,"MENTAL,AURA"
'/t/t',TYPE,SIX,IS,THE,"EMOTIONAL_AURA"
'/t/t',TYPE,SEVEN,IS,THE,"ETHERIC,AURA"
'/t',END,CLASS;
END,COMMAND;

CREATE,NEW,CLASS;'/n'
'/t',NEW,CLASS,SHALL,BE,GIVEN,NAME,"NATURE.CLASSES";
'/t/t',CLASS,SHALL,CONTAIN,THE,NAME,FOR,TWENTYFIVE,DIFFERENT,TYPES,FOR,"HUMAN NATURE"
'/t/t',TYPE,ONE,IS,"ADAMANT"
'/t/t',TYPE,TWO,IS,"BASHFUL"
'/t/t',TYPE,THREE,IS,"BOLD"
'/t/t',TYPE,FOUR,IS,"BRAVE"
'/t/t',TYPE,FIVE,IS,"CALM"
'/t/t',TYPE,SIX,IS,"CAREFUL"
'/t/t',TYPE,SEVEN,IS,"DOCILE"
'/t/t',TYPE,EIGHT,IS,"GENTLE"
'/t/t',TYPE,NINE,IS,"HARDY"
'/t/t',TYPE,TEN,IS,"HASTY"
'/t/t',TYPE,ELEVEN,IS,"IMPISH"
'/t/t',TYPE,TWELVE,IS,"JOLLY"
'/t/t',TYPE,THIRTEEN,IS,"LAX"
'/t/t',TYPE,FOURTEEN,IS,"LONELY"
'/t/t',TYPE,FIFTEEN,IS,"MILD"
'/t/t',TYPE,SIXTEEN,IS,"MODEST"
'/t/t',TYPE,SEVENTEEN,IS,"NAIVE"
'/t/t',TYPE,EIGHTEEN,IS,"NAUGHTY"
'/t/t',TYPE,NINETEEN,IS,"QUIET"
'/t/t',TYPE,TWENTY,IS,"QUIRKY"
'/t/t',TYPE,TWENTYONE,IS,"RASH"
'/t/t',TYPE,TWENTYTWO,IS,"RELAXED"
'/t/t',TYPE,TWENTYTHREE,IS,"SASSY"
'/t/t',TYPE,TWENTYFOUR,IS,"SERIOUS"
'/t/t',TYPE,TWENTYFIVE,IS,"TIMID"
'/t',END,CLASS;
END,COMMAND;

CREATE,NEW,CLASS;'/n'
'/t',NEW,CLASS,SHALL,BE,GIVEN,NAME,"PERSONALITY.CLASSES";
'/t/t',CLASS,SHALL,CONTAIN,THE,NAME,FOR,SIXTEEN,DIFFERENT,TYPES,FOR,PERSONALITY
'/t/t',TYPE,ONE,IS,"INFJ"
'/t/t',TYPE,TWO,IS,"ISFJ"
'/t/t',TYPE,THREE,IS,"INTJ"
'/t/t',TYPE,FOUR,IS,"ISTJ"
'/t/t',TYPE,FIVE,IS,"ISFP"
'/t/t',TYPE,SIX,IS,"INFP"
'/t/t',TYPE,SEVEN,IS,"INTP"
'/t/t',TYPE,EIGHT,IS,"ISTP"
'/t/t',TYPE,NINE,IS,"ENFJ"
'/t/t',TYPE,TEN,IS,"ENFP"
'/t/t',TYPE,ELEVEN,IS,"ESFP"
'/t/t',TYPE,TWELVE,IS,"ESFJ"
'/t/t',TYPE,THIRTEEN,IS,"ENTJ"
'/t/t',TYPE,FOURTEEN,IS,"ENTP"
'/t/t',TYPE,FIFTEEN,IS,"ESTJ"
'/t/t',TYPE,SIXTEEN,IS,"ESTP"
'/t',END,CLASS;
END,COMMAND;

CREATE,NEW,CLASS;'/n'
'/t',NEW,CLASS,SHALL,BE,GIVEN,NAME,"PERSONALITY_TYPE.CLASSES";
'/t/t',CLASS,SHALL,CONTAIN,THE,NAME,FOR,EIGHT,DIFFERENT,SUBTYPES,FOR,PERSONALITY
'/t/t',TYPE,ONE,IS,"INTROVERTED,SENSING"
'/t/t',TYPE,TWO,IS,"EXTRAVERTED,SENSING"
'/t/t',TYPE,THREE,IS,"INTROVERTED,INTUITION"
'/t/t',TYPE,FOUR,IS,"EXTRAVERTED,INTUITION"
'/t/t',TYPE,FIVE,IS,"INTROVERTED,THINKING"
'/t/t',TYPE,SIX,IS,"EXTRAVERTED,THINKING"
'/t/t',TYPE,SEVEN,IS,"INTROVERTED,FEELING"
'/t/t',TYPE,EIGHT,IS,"EXTRAVERTED,FEELING"
'/t',END,CLASS;
END,COMMAND;

CREATE,NEW,CLASS;'/n'
'/t',NEW,CLASS,SHALL,BE,GIVEN,NAME,"PERSONALITY_CATEGORY.CLASSES";
'/t/t',CLASS,SHALL,CONTAIN,THE,NAME,FOR,FOUR,DIFFERENT,SUBTYPES,FOR,PERSONALITY
'/t/t',TYPE,ONE,IS,"SENSING"
'/t/t',TYPE,TWO,IS,"INTUITION"
'/t/t',TYPE,THREE,IS,"THINKING"
'/t/t',TYPE,FOUR,IS,"FEELING"
'/t',END,CLASS;
END,COMMAND;