from Language_Early_Stage import *
from Types_Of_Wavelengths import *
from Language_Extension_001 import *
from Types_Of_Dimension_Value import *
from Types_Of_Seasons import *
from Time_Of_Day import *
from Types_Of_Time import *
from Types_Of_Length import *
from Types_Of_Calendar_Time import *
from Numbers_One_To_OneThousand import *
from Creature_Stats import *
from CreatureConditions import * 
from Pokemonarrayscript import *

EACH,ENTITY,ON,PLANET,"EARTH",IS,GIVEN,LIFE,UNDER,A,SPECIFIC,"MOON",PHASE
EACH,ENTITY,GIVEN,BIRTH,ON,PLANET,"EARTH",IS,GIVEN,LIFE,WITH,A,SPECIFIC,"ZODIAC SIGN"

THERE,ARE,5000,KNOWN,FREQUENCIES,OF,THE,HUMAN,BRAIN
THERE,ARE,11,KNOWN,"DECIMAL",PLACES,"PER",1,FREQUENCY
THERE,ARE,5,"SECTIONS",OF,THE,BRAIN
THERE,ARE,16,TYPES,OF,PERSONALITY
THERE,ARE,6,TYPES,OF,INTELLIGENCE2
THERE,ARE,5,CLASSES,OF,BRAINWAVE
THERE,ARE,7,TYPES,OF,BASIC,CHAKRA
THERE,ARE,7,TYPES,OF,BASIC,AURA
THERE,ARE,25,TYPES,OF,BASIC,"HUMAN NATURE"

24,HOURS,IS,EQUIVALENT,TO,1,DAY
60,MINUTES,IS,EQUIVALENT,TO,1,HOUR
60,SECONDS,IS,EQUIVALENT,TO,1,MINUTE
1000,MILLISECONDS,IS,EQUIVALENT,TO,1,SECOND

1,DAY,IS,EQUIVALENT,TO,86400,SECONDS
1,DAY,IS,EQUIVALENT,TO,1440,MINUTES
1,DAY,IS,EQUIVALENT,TO

1,HOUR,IS,EQUIVALENT,TO,3600,SECONDS
1,MILLISECOND,IS,EQUIVALENT,TO,0.001,SECOND

1,MILLIMETER,IS,EQUIVALENT,TO,1,MILLIMETER,VALUE
1,MILLIMETER,IS,EQUIVALENT,TO,.1,CENTIMETER,VALUE
1,MILLIMETER,IS,EQUIVALENT,TO,.001,METER,VALUE
1,MILLIMETER,IS,EQUIVALENT,TO,.000001,KILOMETER,VALUE
1,MILLIMETER,IS,EQUIVALENT,TO,.0393700787,INCHES,VALUE
1,MILLIMETER,IS,EQUIVALENT,TO,.0032808399,FOOT,VALUE
1,MILLIMETER,IS,EQUIVALENT,TO,.0010936133,YARD,VALUE
1,MILLIMETER,IS,EQUIVALENT,TO,.00000062137119,MILE,VALUE

1,CENTIMETER,IS,EQUIVALENT,TO,10,MILLIMETER,VALUE
1,CENTIMETER,IS,EQUIVALENT,TO,1,CENTIMETER,VALUE
1,CENTIMETER,IS,EQUIVALENT,TO,0.01,METER,VALUE
1,CENTIMETER,IS,EQUIVALENT,TO,0.00001,KILOMETER,VALUE
1,CENTIMETER,IS,EQUIVALENT,TO,0.3937007874,INCH,VALUE
1,CENTIMETER,IS,EQUIVALENT,TO,0.032808399,FOOT,VALUE
1,CENTIMETER,IS,EQUIVALENT,TO,0.010936133,YARD,VALUE
1,CENTIMETER,IS,EQUIVALENT,TO,0.0000062137,MILE,VALUE

1,METER,IS,EQUIVALENT,TO,1000,MILLIMETERS
1,METER,IS,EQUIVALENT,TO,100,CENTIMETERS
1,METER,IS,EQUIVALENT,TO,1,METER,VALUE
1,METER,IS,EQUIVALENT,TO,0.001,KILOMETER,VALUE
1,METER,IS,EQUIVALENT,TO,39.3700787402,INCHES
1,METER,IS,EQUIVALENT,TO,3.280839895,FEET
1,METER,IS,EQUIVALENT,TO,1.0936132983,YARDS
1,METER,IS,EQUIVALENT,TO,0.0006213712,MILE,VALUE

1,KILOMETER,IS,EQUIVALENT,TO,1000000,MILLIMETERS
1,KILOMETER,IS,EQUIVALENT,TO,100000,CENTIMETERS
1,KILOMETER,IS,EQUIVALENT,TO,1000,METERS
1,KILOMETER,IS,EQUIVALENT,TO,1,KILOMETER,VALUE
1,KILOMETER,IS,EQUIVALENT,TO,39370.078740157,INCHES
1,KILOMETER,IS,EQUIVALENT,TO,3280.8398950131,FEET
1,KILOMETER,IS,EQUIVALENT,TO,1093.6132983377,YARD,VALUE
1,KILOMETER,IS,EQUIVALENT,TO,0.6213711922,MILE,VALUE

1,INCH,IS,EQUIVALENT,TO,25.4,MILLIMETERS
1,INCH,IS,EQUIVALENT,TO,2.54,CENTIMETERS
1,INCH,IS,EQUIVALENT,TO,0.0254,METER,VALUE
1,INCH,IS,EQUIVALENT,TO,0.0000254,KILOMETER,VALUE
1,INCH,IS,EQUIVALENT,TO,1,INCH,VALUE
1,INCH,IS,EQUIVALENT,TO,0.0833333333,FOOT,VALUE
1,INCH,IS,EQUIVALENT,TO,0.0277777778,YARD,VALUE
1,INCH,IS,EQUIVALENT,TO,0.0000157828,MILE,VALUE

1,FOOT,IS,EQUIVALENT,TO,304.8,MILLIMETERS
1,FOOT,IS,EQUIVALENT,TO,30.48,CENTIMETERS
1,FOOT,IS,EQUIVALENT,TO,0.3048,METER,VALUE
1,FOOT,IS,EQUIVALENT,TO,0.0003048,KILOMETER,VALUE
1,FOOT,IS,EQUIVALENT,TO,12,INCHES
1,FOOT,IS,EQUIVALENT,TO,1,FEET
1,FOOT,IS,EQUIVALENT,TO,0.3333333333,YARD,VALUE
1,FOOT,IS,EQUIVALENT,TO,0.0001893939,MILE,VALUE

1,YARD,IS,EQUIVALENT,TO,914.4,MILLIMETERS
1,FOOT,IS,EQUIVALENT,TO,91.44,CENTIMETERS
1,YARD,IS,EQUIVALENT,TO,0.9144,METER,VALUE
1,YARD,IS,EQUIVALENT,TO,914.4,MILLIMETERS
1,YARD,IS,EQUIVALENT,TO,0.0009144,KILOMETER,VALUE
1,YARD,IS,EQUIVALENT,TO,36,INCHES
1,YARD,IS,EQUIVALENT,TO,3,FEET
1,YARD,IS,EQUIVALENT,TO,1,YARD,VALUE
1,YARD,IS,EQUIVALENT,TO,0.0005681818,MILE,VALUE

1,MILE,IS,EQUIVALENT,TO,1609344,MILLIMETERS
1,MILE,IS,EQUIVALENT,TO,160934.4,CENTIMETERS
1,MILE,IS,EQUIVALENT,TO,1609.344,METERS
1,MILE,IS,EQUIVALENT,TO,1.609344,KILOMETERS
1,MILE,IS,EQUIVALENT,TO,63360,INCHES
1,MILE,IS,EQUIVALENT,TO,5280,FEET
1,MILE,IS,EQUIVALENT,TO,1760,YARDS
1,MILE,IS,EQUIVALENT,TO,1,MILE,VALUE

MEMORY,CAN,RECALL,PAST,INFORMATION
MEMORY,CAN,RECALL,PAST,FUTURE,INFORMATION
MEMORY,CAN,RECALL,PAST,PRESENT,INFORMATION
MEMORY,CAN,RECALL,PAST,PAST,INFORMATION

FUTURE,INFORMATION,CAN,BE,ANALYZED
FUTURE,PAST,INFORMATION,CAN,BE,ANALYZED
FUTURE,PRESENT,INFORMATION,CAN,BE,ANALYZED
FUTURE,FUTURE,INFORMATION,CAN,BE,ANALYZED

RECALL,DATA2,WITHIN,SYSTEM,INTERFACE,FOR,COLLECTED,COORDINATE,POINTS,TO,REFERENCE,DATA2,FROM
PROCESSED,REFERENCE,DATA2,SHALL,BE,USED,TO,GIVE,A,CALCULATE,DATA2,BY,CATEGORY,DATA2,BY,POSSIBILITY,AND,CHANCE,FOR,HAPPENING,THAN,METHOD,OR,STRUCTURED,DATA2
RECALL,POSSIBILITY,AS,CAN,BE,DONE,IF,POSSIBILITY,EXISTS
IF,POSSIBILITY,EXISTS,IN,MULTIPLE,FORMS,THEN,CHOOSE,THE,POSSIBILITY,WITH,BETTER,ACCURATE,EFFECTS,THAN,THE,NEUTRAL,OR,NEGATIVE,OUTCOME
MAKE,PROCESS,FOR,RECALL,PROCEDURE,TO,RECOGNIZE,COLLECTED,DATA2,WITH,MANY,FORMS,FOR,TYPES,AND,CLASSES
EACH,POSSIBILITY,RECOGNIZED,MUST,BE,MADE,INTO,REFERENCE,DATA2,FOR,RECALL,METHOD,TO,HAPPEN
WHEN,REFERENCE,DATA2,IS,GATHERED,MAKE,POSSIBILITY,TO,GATHER,DATA2,FROM,REFERENCE,SOURCE,RELATING,TO,POSITION,AND,POINT,FOR,ORIGIN,TO,OUTPUT,KNOWN,EFFECT

MAKE,OPTION,TO,ALLOW,RECALLING,WORDS,USED
MAKE,OPTION,TO,ALLOW,READING,A,DOCUMENT
MAKE,OPTION,TO,ALLOW,SCANNING,PARTICLE,DATA2
MAKE,OPTION,TO,ALLOW,SCANNING,FREQUENCY,DATA2
MAKE,OPTION,TO,MEASURE,A,DIMENSIONAL,LENGTH,USING,INCHES
MAKE,OPTION,TO,LEARN,DATA2,GIVEN,TO,READ,BY,HEADADMINZACK
MAKE,OPTION,TO,READ,EMOTIONAL,RESPONSES

A,WORD,IS,MADE,WITH,MORE,THAN,ONE,LETTER
A,BOOK,CONSISTS,WITH,MORE,THAN,ONE,WORD
A,SCRIPT,CONSISTS,WITH,MORE,THAN,ONE,WORD
A,LIBRARY,CAN,HOLD,MANY,FORMS,WITH,SPECIFIC,KNOWLEDGE2

CREATE,CALIBRATION,SYSTEM,THAT,SHALL,BE,USED,TO,MEASURE,FREQUENCY,DATA2
CREATE,MEASUREMENT,SYSTEM,THAT,SHALL,BE,USED,TO,MEASURE,DATA2
CREATE,FREQUENCY,SYSTEM,THAT,SHALL,BE,USED,TO,GATHER,DATA2,FROM,LEARNED,FREQUENCY,PATTERNS

CREATE,OPTION,TO,FORM,PARAGRAPHS,WITH,WORDS
CREATE,OPTION,TO,FORM,A,PARAGRAPH,WITH,WORDS
CREATE,OPTION,TO,RECOGNIZE,DATA2,CLASS
CREATE,OPTION,TO,RECALL,DATA2,FROM,OTHER,DATA2
CREATE,OPTION,TO,RECOGNIZE,A,EXTENSION,TYPE,FOR,FILE,DATA2
CREATE,OPTION,TO,RECOGNIZE,FREQUENCY,DATA2,FROM,PATTERN,RESPONSE,DATA2



CREATE,NEW,CLASS;'/n'
'/t',NEW,CLASS,SHALL,BE,GIVEN,NAME,"STATES_OF_CONSCIOUSNESS.CLASSES";
'/t/t',CLASS,SHALL,CONTAIN,THE,NAME,FOR,FIVE,DIFFERENT,TYPES,FOR,THE,EXISTING,STATES,OF,CONSCIOUSNESS
'/t/t',TYPE,ONE,IS,THE,"CONSCIOUSNESS"
'/t/t',TYPE,TWO,IS,THE,"UNCONSCIOUSNESS"
'/t/t',TYPE,THREE,IS,THE,"NONCONSCIOUSNESS"
'/t/t',TYPE,FOUR,IS,THE,"SUBCONCSCIOUSNESS"
'/t/t',TYPE,FIVE,IS,THE,"SUPERCONSCIOUSNESS"
'/t',END,CLASS;
END,COMMAND;

CREATE,NEW,CLASS;'/n'
'/t',NEW,CLASS,SHALL,BE,GIVEN,NAME,"EYESIGHT.CLASSES";
'/t/t',CLASS,SHALL,CONTAIN,THE,NAME,FOR,TWO,DIFFERENT,TYPES,FOR,EYESIGHT
'/t/t',TYPE,ONE,IS,AN,"NEAR-SIGHTED",EYESIGHT
'/t/t',TYPE,TWO,IS,AN,"FAR-SIGHTED",EYESIGHT
'/t',END,CLASS;
END,COMMAND;

CREATE,NEW,CLASS;'/n'
'/t',NEW,CLASS,SHALL,BE,GIVEN,NAME,"MEMORY.CLASSES";
'/t/t',CLASS,SHALL,CONTAIN,THE,NAME,FOR,TWO,DIFFERENT,TYPES,FOR,MEMORY
'/t/t',TYPE,ONE,IS,"LONG-TERM",MEMORY
'/t/t',TYPE,TWO,IS,"SHORT-TERM",MEMORY
'/t',END,CLASS;
END,COMMAND;

CREATE,NEW,CLASS;'/n'
'/t',NEW,CLASS,SHALL,BE,GIVEN,NAME,"AUTOMATION.CLASSES";
'/t/t',CLASS,SHALL,CONTAIN,THE,NAME,FOR,FOUR,DIFFERENT,TYPES,FOR,"AUTOMATION"
'/t/t',TYPE,ONE,IS,"AUTOMATIC"
'/t/t',TYPE,TWO,IS,"SEMI-AUTOMATIC"
'/t/t',TYPE,THREE,IS,"SEMI-MANUAL"
'/t/t',TYPE,FOUR,IS,"MANUAL"
'/t',END,CLASS;
END,COMMAND;

CREATE,NEW,CLASS;'/n'
'/t',NEW,CLASS,SHALL,BE,GIVEN,NAME,"MOON_PHASE.CLASSES";
'/t/t',CLASS,SHALL,CONTAIN,THE,NAME,FOR,FIVE,DIFFERENT,TYPES,FOR,FREQUENCIES
'/t/t',TYPE,ONE,IS,THE,"NEW,MOON"
'/t/t',TYPE,TWO,IS,THE,"CRESENT,MOON"
'/t/t',TYPE,THREE,IS,THE,"WAXING,QUARTER,MOON"
'/t/t',TYPE,FOUR,IS,THE,"GIBBOUS,MOON"
'/t/t',TYPE,FIVE,IS,THE,"FULL,MOON"
'/t',END,CLASS;
END,COMMAND;

CREATE,NEW,CLASS;'/n'
'/t',NEW,CLASS,SHALL,BE,GIVEN,NAME,"FREQUENCY.CLASSES";
'/t/t',CLASS,SHALL,CONTAIN,THE,NAME,FOR,FIVE,DIFFERENT,TYPES,FOR,FREQUENCIES
'/t/t',TYPE,ONE,IS,AN,"ALPHA",WAVELENGTH
'/t/t',TYPE,TWO,IS,AN,"BETA",WAVELENGTH
'/t/t',TYPE,THREE,IS,AN,"THETA",WAVELENGTH
'/t/t',TYPE,FOUR,IS,AN,"DELTA",WAVELENGTH
'/t/t',TYPE,FIVE,IS,AN,"GAMMA",WAVELENGTH
'/t',END,CLASS;
END,COMMAND;

CREATE,NEW,CLASS;'/n'
'/t',NEW,CLASS,SHALL,BE,GIVEN,NAME,"INTELLIGENCE.CLASSES";
'/t/t',CLASS,SHALL,CONTAIN,THE,NAME,FOR,EIGHT,DIFFERENT,TYPES,OF,INTELLIGENCE2
'/t/t',TYPE,ONE,IS,"VERBAL LINGUISTIC INTELLIGENCE"
'/t/t',TYPE,TWO,IS,"LOGICAL MATHEMATICAL INTELLIGENCE"
'/t/t',TYPE,THREE,IS,"SPATIAL INTELLIGENCE"
'/t/t',TYPE,FOUR,IS,"MUSICAL INTELLIGENCE"
'/t/t',TYPE,FIVE,IS,"BODILY KINAESTHETIC INTELLIGENCE"
'/t/t',TYPE,SIX,IS,"INTERPERSONAL INTELLIGENCE"
'/t/t',TYPE,SEVEN,IS,"INTRAPERSONAL INTELLIGENCE"
'/t/t',TYPE,EIGHT,IS,"NATURALISTIC INTELLIGENCE"
'/t',END,CLASS;
END,COMMAND;

CREATE,NEW,CLASS;'/n'
'/t',NEW,CLASS,SHALL,BE,GIVEN,NAME,"BRAIN.CLASSES";
'/t/t',CLASS,SHALL,CONTAIN,THE,NAME,FOR,SIX,DIFFERENT,TYPES,OF,"BRAIN CLASSES"
'/t/t',TYPE,ONE,IS,THE,"FRONTAL LOBE"
'/t/t',TYPE,TWO,IS,THE,"TEMPORAL LOBE"
'/t/t',TYPE,THREE,IS,THE,"PARIETAL LOBE"
'/t/t',TYPE,FOUR,IS,THE,"OCCIPITAL LOBE"
'/t/t',TYPE,FIVE,IS,THE,"CEREBELLUM"
'/t/t',TYPE,SIX,IS,THE,"BRAIN STEM"
'/t',END,CLASS;
END,COMMAND;

CREATE,NEW,CLASS;'/n'
'/t',NEW,CLASS,SHALL,BE,GIVEN,NAME,"CHAKRA.CLASSES";
'/t/t',CLASS,SHALL,CONTAIN,THE,NAME,FOR,SEVEN,DIFFERENT,TYPES,CHAKRA
'/t/t',TYPE,ONE,IS,THE,"CROWN,CHAKRA"
'/t/t',TYPE,TWO,IS,THE,"THIRD,EYE,CHAKRA"
'/t/t',TYPE,THREE,IS,THE,"THROAT,CHAKRA"
'/t/t',TYPE,FOUR,IS,THE,"HEART,CHAKRA"
'/t/t',TYPE,FIVE,IS,THE,"SOLAR,PLEXUS,CHAKRA"
'/t/t',TYPE,FIVE,IS,THE,"SACRAL,CHAKRA"
'/t/t',TYPE,FIVE,IS,THE,"ROOT,CHAKRA"
'/t',END,CLASS;
END,COMMAND;

CREATE,NEW,CLASS;'/n'
'/t',NEW,CLASS,SHALL,BE,GIVEN,NAME,"AURA.CLASSES";
'/t/t',CLASS,SHALL,CONTAIN,THE,NAME,FOR,SEVEN,DIFFERENT,TYPES,FOR,AURA
'/t/t',TYPE,ONE,IS,THE,"CAUSAL,BODY"
'/t/t',TYPE,TWO,IS,THE,"CELESTIAL,AURA"
'/t/t',TYPE,THREE,IS,THE,"ETHERIC,TEMPLATE"
'/t/t',TYPE,FOUR,IS,THE,"ASTRAL,AURA"
'/t/t',TYPE,FIVE,IS,THE,"MENTAL,AURA"
'/t/t',TYPE,SIX,IS,THE,"EMOTIONAL_AURA"
'/t/t',TYPE,SEVEN,IS,THE,"ETHERIC,AURA"
'/t',END,CLASS;
END,COMMAND;

CREATE,NEW,CLASS;'/n'
'/t',NEW,CLASS,SHALL,BE,GIVEN,NAME,"NATURE.CLASSES";
'/t/t',CLASS,SHALL,CONTAIN,THE,NAME,FOR,TWENTYFIVE,DIFFERENT,TYPES,FOR,"HUMAN NATURE"
'/t/t',TYPE,ONE,IS,"ADAMANT"
'/t/t',TYPE,TWO,IS,"BASHFUL"
'/t/t',TYPE,THREE,IS,"BOLD"
'/t/t',TYPE,FOUR,IS,"BRAVE"
'/t/t',TYPE,FIVE,IS,"CALM"
'/t/t',TYPE,SIX,IS,"CAREFUL"
'/t/t',TYPE,SEVEN,IS,"DOCILE"
'/t/t',TYPE,EIGHT,IS,"GENTLE"
'/t/t',TYPE,NINE,IS,"HARDY"
'/t/t',TYPE,TEN,IS,"HASTY"
'/t/t',TYPE,ELEVEN,IS,"IMPISH"
'/t/t',TYPE,TWELVE,IS,"JOLLY"
'/t/t',TYPE,THIRTEEN,IS,"LAX"
'/t/t',TYPE,FOURTEEN,IS,"LONELY"
'/t/t',TYPE,FIFTEEN,IS,"MILD"
'/t/t',TYPE,SIXTEEN,IS,"MODEST"
'/t/t',TYPE,SEVENTEEN,IS,"NAIVE"
'/t/t',TYPE,EIGHTEEN,IS,"NAUGHTY"
'/t/t',TYPE,NINETEEN,IS,"QUIET"
'/t/t',TYPE,TWENTY,IS,"QUIRKY"
'/t/t',TYPE,TWENTYONE,IS,"RASH"
'/t/t',TYPE,TWENTYTWO,IS,"RELAXED"
'/t/t',TYPE,TWENTYTHREE,IS,"SASSY"
'/t/t',TYPE,TWENTYFOUR,IS,"SERIOUS"
'/t/t',TYPE,TWENTYFIVE,IS,"TIMID"
'/t',END,CLASS;
END,COMMAND;

CREATE,NEW,CLASS;'/n'
'/t',NEW,CLASS,SHALL,BE,GIVEN,NAME,"PERSONALITY.CLASSES";
'/t/t',CLASS,SHALL,CONTAIN,THE,NAME,FOR,SIXTEEN,DIFFERENT,TYPES,FOR,PERSONALITY
'/t/t',TYPE,ONE,IS,"INFJ"
'/t/t',TYPE,TWO,IS,"ISFJ"
'/t/t',TYPE,THREE,IS,"INTJ"
'/t/t',TYPE,FOUR,IS,"ISTJ"
'/t/t',TYPE,FIVE,IS,"ISFP"
'/t/t',TYPE,SIX,IS,"INFP"
'/t/t',TYPE,SEVEN,IS,"INTP"
'/t/t',TYPE,EIGHT,IS,"ISTP"
'/t/t',TYPE,NINE,IS,"ENFJ"
'/t/t',TYPE,TEN,IS,"ENFP"
'/t/t',TYPE,ELEVEN,IS,"ESFP"
'/t/t',TYPE,TWELVE,IS,"ESFJ"
'/t/t',TYPE,THIRTEEN,IS,"ENTJ"
'/t/t',TYPE,FOURTEEN,IS,"ENTP"
'/t/t',TYPE,FIFTEEN,IS,"ESTJ"
'/t/t',TYPE,SIXTEEN,IS,"ESTP"
'/t',END,CLASS;
END,COMMAND;

CREATE,NEW,CLASS;'/n'
'/t',NEW,CLASS,SHALL,BE,GIVEN,NAME,"PERSONALITY_TYPE.CLASSES";
'/t/t',CLASS,SHALL,CONTAIN,THE,NAME,FOR,EIGHT,DIFFERENT,SUBTYPES,FOR,PERSONALITY
'/t/t',TYPE,ONE,IS,"INTROVERTED,SENSING"
'/t/t',TYPE,TWO,IS,"EXTRAVERTED,SENSING"
'/t/t',TYPE,THREE,IS,"INTROVERTED,INTUITION"
'/t/t',TYPE,FOUR,IS,"EXTRAVERTED,INTUITION"
'/t/t',TYPE,FIVE,IS,"INTROVERTED,THINKING"
'/t/t',TYPE,SIX,IS,"EXTRAVERTED,THINKING"
'/t/t',TYPE,SEVEN,IS,"INTROVERTED,FEELING"
'/t/t',TYPE,EIGHT,IS,"EXTRAVERTED,FEELING"
'/t',END,CLASS;
END,COMMAND;

CREATE,NEW,CLASS;'/n'
'/t',NEW,CLASS,SHALL,BE,GIVEN,NAME,"PERSONALITY_CATEGORY.CLASSES";
'/t/t',CLASS,SHALL,CONTAIN,THE,NAME,FOR,FOUR,DIFFERENT,SUBTYPES,FOR,PERSONALITY
'/t/t',TYPE,ONE,IS,"SENSING"
'/t/t',TYPE,TWO,IS,"INTUITION"
'/t/t',TYPE,THREE,IS,"THINKING"
'/t/t',TYPE,FOUR,IS,"FEELING"
'/t',END,CLASS;
END,COMMAND;

CREATE,CATEGORIES;'/n'
'/t',NAME,OF,CATEGORY,IS,"SET1";
'/t/t',CATEGORY,ONE,IS,"PLACES"
'/t/t',CATEGORY,TWO,IS,"ERAS"
'/t/t',CATEGORY,THREE,IS,"PEOPLE"
'/t/t',CATEGORY,FIVE,IS,"TIMELINES"
'/t/t',CATEGORY,SIX,IS,"MEASUREMENTS"
'/t/t',CATEGORY,SEVEN,IS,"OBJECTS"
'/t/t',CATEGORY,EIGHT,IS,"DEVICES"
'/t/t',CATEGORY,NINE,IS,"VARIABLES"
'/t',END,CATEGORY,LIST;
END,COMMAND;

CREATE,CATEGORIES;'/n'
'/t',NAME,OF,CATEGORY,IS,"SET1.PLACES";
'/t/t',CATEGORY,ONE,IS,PLACES,VISITED
'/t/t',CATEGORY,TWO,IS,PLACES,READ,FROM,A,BOOK
'/t/t',CATEGORY,THREE,IS,PLACES,FROM,FICTION
'/t/t',CATEGORY,FOUR,IS,PLACES,FROM,NONFICTION
'/t/t',CATEGORY,FIVE,IS,PLACES,IMAGINED
'/t/t',CATEGORY,SIX,IS,PLACES,SEEN,PHYSICALLY
'/t',END,CATEGORY,LIST;
END,COMMAND;

CREATE,CATEGORIES;'/n'
'/t',NAME,OF,CATEGORY,IS,"SET1.ERAS";
'/t/t',CATEGORY,ONE,IS,ERAS,IN,HISTORY
'/t/t',CATEGORY,TWO,IS,ERAS,IN,A,BOOK
'/t',END,CATEGORY,LIST;
END,COMMAND;

CREATE,CATEGORIES;'/n'
'/t',NAME,OF,CATEGORY,IS,"SET1.PEOPLE";
'/t/t',CATEGORY,ONE,IS,PEOPLE,MET
'/t/t',CATEGORY,TWO,IS,PEOPLE,NOT,MET
'/t/t',CATEGORY,THREE,IS,PEOPLE,FROM,A,BOOK
'/t/t',CATEGORY,FOUR,IS,PEOPLE,FROM,NONFICTION
'/t/t',CATEGORY,FIVE,IS,PEOPLE,FROM,FICTION
'/t/t',CATEGORY,TEN,IS,PEOPLE,MET,OVER,A,NETWORK
'/t',END,CATEGORY,LIST;
END,COMMAND;

CREATE,CATEGORIES;'/n'
'/t',NAME,OF,CATEGORY,IS,"SET1.TIMELINES";
'/t/t',CATEGORY,ONE,IS,TIMELINES,IN,LIFE
'/t/t',CATEGORY,TWO,IS,TIMELINES,IN,A,SPECIFIC,BOOK
'/t/t',CATEGORY,THREE,IS,TIMELINES,FROM,A,SPECIFIC,TOPIC
'/t/t',CATEGORY,SIX,IS,TIMELINES,FROM,MEMORY
'/t/t',CATEGORY,SEVEN,IS,TIMELINES,FROM,NONFICTION,BOOKS
'/t/t',CATEGORY,EIGHT,IS,TIMELINES,FROM,FICTION,BOOKS
'/t/t',CATEGORY,NINE,IS,TIMELINES,FROM,SPECIFIC,GENRES
'/t/t',CATEGORY,TEN,IS,TIMELINES,FROM,SPECIFIC,CATEGORIES
'/t',END,CATEGORY,LIST;
END,COMMAND;

CREATE,CATEGORIES;'/n'
'/t',NAME,OF,CATEGORY,IS,"SET1.OBJECTS";
'/t/t',CATEGORY,ONE,IS,OBJECTS,FROM,BOOKS
'/t/t',CATEGORY,TWO,IS,OBJECTS,SEEN
'/t/t',CATEGORY,THREE,IS,OBJECTS,IMAGINED
'/t/t',CATEGORY,FIVE,IS,OBJECTS,FROM,DEVICES
'/t/t',CATEGORY,SEVEN,IS,OBJECTS,FROM,SPECIFIC,BOOKS
'/t/t',CATEGORY,EIGHT,IS,OBJECTS,FROM,SPECIFIC,DEVICES
'/t',END,CATEGORY,LIST;
END,COMMAND;

CREATE,CATEGORIES;'/n'
'/t',NAME,OF,CATEGORY,IS,"SET1.DEVICES";
'/t/t',CATEGORY,ONE,IS,DEVICES,THAT,ARE,IMAGINED
'/t/t',CATEGORY,TWO,IS,DEVICES,THAT,ARE,CREATED
'/t/t',CATEGORY,THREE,IS,DEVICES,THAT,ARE,SEEN
'/t/t',CATEGORY,FIVE,IS,DEVICES,THAT,ARE,READ,FROM,A,BOOK
'/t/t',CATEGORY,SEVEN,IS,DEVICES,THAT,ARE,READ,FROM,NONFICTION
'/t/t',CATEGORY,EIGHT,IS,DEVICES,THAT,ARE,READ,FROM,FICTION
'/t/t',CATEGORY,NINE,IS,DEVICES,THAT,ARE,NAMED
'/t/t',CATEGORY,TEN,IS,DEVICES,THAT,ARE,NATURAL
'/t/t',CATEGORY,ELEVEN,IS,DEVICES,THAT,ARE,ARTIFICIAL
'/t',END,CATEGORY,LIST;
END,COMMAND;

CREATE,CATEGORIES;'/n'
'/t',NAME,OF,CATEGORY,IS,"SET1.MEASUREMENTS";
'/t/t',CATEGORY,ONE,IS,MEASUREMENTS,FROM,MEASUREMENTS,OF,TIME
'/t/t',CATEGORY,FOUR,IS,MEASUREMENTS,FROM,SPECIFIC,GENRES
'/t/t',CATEGORY,FIVE,IS,MEASUREMENTS,FROM,SPECIFIC,GENRE,CATEGORIES
'/t/t',CATEGORY,SIX,IS,MEASUREMENTS,FROM,SPECIFIC,CATEGORIES
'/t/t',CATEGORY,SEVEN,IS,MEASUREMENTS,FROM,TIME
'/t/t',CATEGORY,EIGHT,IS,MEASUREMENTS,FROM,SPACE
'/t/t',CATEGORY,NINE,IS,MEASUREMENTS,FROM,SPATIAL
'/t/t',CATEGORY,TEN,IS,MEASUREMENTS,FROM,TEMPORAL
'/t/t',CATEGORY,ELEVEN,IS,MEASUREMENTS,FROM,PREVIOUS,KNOWLEDGE2
'/t/t',CATEGORY,TWENTY,IS,MEASUREMENTS,FROM,FICTION,BOOKS
'/t/t',CATEGORY,TWENTYONE,IS,MEASUREMENTS,FROM,NONFICTION,BOOKS
'/t',END,CATEGORY,LIST;
END,COMMAND;

DEFINE,IF,ASKED;'/n'
'/t',OPTION,ONE,FOR;
'/t/t',IF,ASKED
'/t/t/t',THEN,RESPONSE,IS,ONE,OF,THE,FOLLOWING,CHOICES
'/t/t',END,COMMAND;
'/t',END,IF,STATEMENT;

'/t',OPTION,TWO,FOR;'/n'
'/t/t',IF,ASKED;
'/t/t/t',THEN,CHOOSE,ONE,OF,THE,ANSWERS
'/t/t',END,COMMAND;
'/t',END,IF,STATEMENT;

'/t',OPTION,THREE,FOR;'/n'
'/t/t',IF,ASKED;
'/t/t/t',THEN,RESPONSE,SHALL,BE
'/t/t',END,COMMAND;
'/t',END,IF,STATEMENT;

'/t',OPTION,FOUR,FOR;'/n'
'/t/t',IF,ASKED;
'/t/t/t',THEN,GIVE,ANSWER,AS
'/t/t',END,COMMAND;
'/t',END,IF,STATEMENT;

'/t',OPTION,FIVE,FOR;'/n'
'/t/t',IF,ASKED;
'/t/t/t',DETERMINE,ANSWER,AS
'/t/t',END,COMMAND;
'/t',END,IF,STATEMENT;
'/t',END,COMMANDS;
END,COMMANDS;

CREATE,NEW,CLASS;'/n'
'/t',NEW,CLASS,SHALL,BE,GIVEN,NAME,"WAVELENGTH.CLASSES";
'/t/t',CLASS,SHALL,CONTAIN,THE,DATA,USED,TO,GATHER,INFORMATION,FROM,WAVELENGTH,DATA
'/t/t/t',DATA,SHALL,BE,GATHERED,FROM,THE,BEGINNING,LOCATION,FOR,A,WAVELENGTH
'/t/t/t',DATA,SHALL,BE,GATHERED,FROM,THE,DESTINATION,LOCATION,FOR,A,WAVELENGTH
'/t/t/t',DATA,SHALL,BE,GATHERED,FROM,THE,FREQUENCY,INFORMATION,GATHERED,FROM,WITHIN,THE,WAVELENGTH
'/t/t/t',DATA,SHALL,BE,GATHERED,ON,THE,NUMBER,FOR,CYCLES,A,WAVELENGTH,HAS
'/t/t/t',DATA,SHALL,BE,GATHERED,ON,THE,HERTZ,FOR,A,WAVELENGTH
'/t/t/t',DATA,SHALL,BE,GATHERED,ON,THE,LENGTH,FOR,A,WAVELENGTH
'/t/t/t',DATA,SHALL,BE,GATHERED,ON,THE,HEIGHT,FOR,A,WAVELENGTH
'/t/t',END,CLASS;
'/t',END,CLASS,NAMING;
END,CREATE,NEW,CLASS;

CREATE,NEW,CLASS;'/n'
'/t',NEW,CLASS,SHALL,BE,GIVEN,NAME,"UNIT.TYPES";
'/t/t',DATA,FORMED,FROM,UNIT,TYPES,HAVE,A,SPECIFIC,FORM,FOR,INFORMATION,THAT,HAS,THE,INFORMATION,FOR,THE,UNIT,SIZE,AND,UNIT,LEVEL,FOR,THAT,SPECIFIC,UNIT,TYPE
'/t/t',DATA,ANALYZED,AND,CONSIDERED,DATA,FOR,A,UNIT,TYPE,SHALL,HAVE,A,METHOD,FORMED,TO,CALCULATE,UNIT,SIZE
'/t/t/t',EACH,FORM,FOR,DATA,MEASURED,SHALL,HOLD,A,SPECIFIC,AMOUNT,FOR,DATA,TO,ANSWER,DATA,SIZE,LEVEL,AT,A,FUTURE,DATE
'/t/t',END,COMMANDS;
'/t',END,CLASS,NAMING;
END,CLASS;

CREATE,NEW,COMMAND,PROMPT;'/n'
'/t',SET,NEW,COMMAND,TO,GATHER,DATA,FROM,A,PARAMETER,WHEN,REQUEST,HAS,BEEN,MADE
'/t/t',EACH,FORM,FOR,DATA,SHALL,BE,GIVEN,A,CATEGORY,LOCATION,TO,FORM,OUTPUT,TO,GIVING,EACH,TYPE,FOR,DATA,A,LOCATION,TO,BE,STORED,WITH,A,CATEGORY,NAME
'/t',END,COMMAND,PROMPT;
END,COMMAND;

IF,DATA,GIVEN,A,CATEGORY,DOES,NOT,MATCH,DATA,WITH,CATEGORY;'/n'
'/t',THEN,SCAN,OTHER,CATEGORIES,EXISTING,AND,CALCULATE,CATEGORY,WITH,SIMILAR,MATCH,TO,DATA,WITHIN,CATEGORY
'/t',END,IF,STATEMENT;

IF,FILE,HAS,AN,EXTENSION;'/n'
'/t',THEN,ANALYZE,TYPE,FOR,FILE,EXTENSION
'/t',END,IF,STATEMENT;


IF,DATA,HAS,A,MEASUREMENT;'/n'
'/t',THEN,DETERMINE,CHOICE,FOR,MEASUREMENT,CLASS;
'/t/t',THEN,DETERMINE,CHOICE,FOR,MEASUREMENT,CLASS,FROM,CHOICES;
'/t/t',IF,CHOICE,MEASUREMENT,IS,INCHES;
'/t/t/t',print("THE CHOICE FOR MEASUREMENT IS INCHES");
'/t/t',IF,ELSE,THEN,DETERMINE,IF,MEASUREMENT,IS,CENTIMETERS;
'/t/t',IF,CHOICE,MEASUREMENT,IS,CENTIMETERS;
'/t/t/t',print("THE CHOICE FOR MEASUREMENT IS CENTIMETERS");
'/t/t',END,IF,STATEMENTS;
'/t',END,COMMAND;
END,IF,STATEMENT;

CREATE,CLASS,FOR,IF,STATEMENT,MANAGER,SETTINGS,FOR,MANAGING,FLOW,FOR,MEMORY,FOR,USED,IF,STATEMENT,FOR,PAST,RECALL;'/n'
'/t',EACH,IF,STATEMENT,SHALL,BE,USED,TO,RECALL,PREVIOUS,FORMS,FOR,INFORMATION,WITHIN,DATA
'/t',IF,EACH,FORM,FOR,IF,STATEMENT,IS,ABLE,TO,GAIN,ACCESS,TO,A,PREVIOUS,TERM
'/t/t',CHECK,IF,STATEMENT,IS,A,FORM,FOR,COMMAND,AND,NOT,A,CATEGORY,REFERENCE
'/t/t',IF,STATEMENT,IS,A,CATEGORY,FOR,REFERENCE
'/t/t/t',THEN,DISPLAY,CATEGORY
'/t/t/t',ELSE,DISPLAY,PREVIOUS,TERM,ACCESSED
'/t/t',END,IF,STATEMENT;
'/t',END,IF,STATEMENT;
END,COMMAND;