from Language_Early_Stage import *
from Types_Of_Wavelengths import *
from Language_Extension_001 import *
from Types_Of_Dimension_Value import *
from Types_Of_Seasons import *
from Time_Of_Day import *
from Types_Of_Time import *
from Types_Of_Length import *
from Types_Of_Calendar_Time import *
from Numbers_One_To_OneThousand import *
from Creature_Stats import *
from CreatureConditions import * 
from Pokemonarrayscript import *

EACH,ENTITY,ON,PLANET,"EARTH",IS,GIVEN,LIFE,UNDER,A,SPECIFIC,"MOON",PHASE
EACH,ENTITY,GIVEN,BIRTH,ON,PLANET,"EARTH",IS,GIVEN,LIFE,WITH,A,SPECIFIC,"ZODIAC SIGN"

THERE,ARE,5000,KNOWN,FREQUENCIES,OF,THE,HUMAN,BRAIN
THERE,ARE,11,KNOWN,"DECIMAL",PLACES,"PER",1,FREQUENCY
THERE,ARE,5,"SECTIONS",OF,THE,BRAIN
THERE,ARE,16,TYPES,OF,PERSONALITY
THERE,ARE,6,TYPES,OF,INTELLIGENCE2
THERE,ARE,5,CLASSES,OF,BRAINWAVE
THERE,ARE,7,TYPES,OF,BASIC,CHAKRA
THERE,ARE,7,TYPES,OF,BASIC,AURA
THERE,ARE,25,TYPES,OF,BASIC,"HUMAN NATURE"

24,HOURS,IS,EQUIVALENT,TO,1,DAY
60,MINUTES,IS,EQUIVALENT,TO,1,HOUR
60,SECONDS,IS,EQUIVALENT,TO,1,MINUTE
1000,MILLISECONDS,IS,EQUIVALENT,TO,1,SECOND

1,DAY,IS,EQUIVALENT,TO,86400,SECONDS
1,DAY,IS,EQUIVALENT,TO,1440,MINUTES
1,DAY,IS,EQUIVALENT,TO

1,HOUR,IS,EQUIVALENT,TO,3600,SECONDS
1,MILLISECOND,IS,EQUIVALENT,TO,0.001,SECOND

1,MILLIMETER,IS,EQUIVALENT,TO,1,MILLIMETER,VALUE
1,MILLIMETER,IS,EQUIVALENT,TO,.1,CENTIMETER,VALUE
1,MILLIMETER,IS,EQUIVALENT,TO,.001,METER,VALUE
1,MILLIMETER,IS,EQUIVALENT,TO,.000001,KILOMETER,VALUE
1,MILLIMETER,IS,EQUIVALENT,TO,.0393700787,INCHES,VALUE
1,MILLIMETER,IS,EQUIVALENT,TO,.0032808399,FOOT,VALUE
1,MILLIMETER,IS,EQUIVALENT,TO,.0010936133,YARD,VALUE
1,MILLIMETER,IS,EQUIVALENT,TO,.00000062137119,MILE,VALUE

1,CENTIMETER,IS,EQUIVALENT,TO,10,MILLIMETER,VALUE
1,CENTIMETER,IS,EQUIVALENT,TO,1,CENTIMETER,VALUE
1,CENTIMETER,IS,EQUIVALENT,TO,0.01,METER,VALUE
1,CENTIMETER,IS,EQUIVALENT,TO,0.00001,KILOMETER,VALUE
1,CENTIMETER,IS,EQUIVALENT,TO,0.3937007874,INCH,VALUE
1,CENTIMETER,IS,EQUIVALENT,TO,0.032808399,FOOT,VALUE
1,CENTIMETER,IS,EQUIVALENT,TO,0.010936133,YARD,VALUE
1,CENTIMETER,IS,EQUIVALENT,TO,0.0000062137,MILE,VALUE

1,METER,IS,EQUIVALENT,TO,1000,MILLIMETERS
1,METER,IS,EQUIVALENT,TO,100,CENTIMETERS
1,METER,IS,EQUIVALENT,TO,1,METER,VALUE
1,METER,IS,EQUIVALENT,TO,0.001,KILOMETER,VALUE
1,METER,IS,EQUIVALENT,TO,39.3700787402,INCHES
1,METER,IS,EQUIVALENT,TO,3.280839895,FEET
1,METER,IS,EQUIVALENT,TO,1.0936132983,YARDS
1,METER,IS,EQUIVALENT,TO,0.0006213712,MILE,VALUE

1,KILOMETER,IS,EQUIVALENT,TO,1000000,MILLIMETERS
1,KILOMETER,IS,EQUIVALENT,TO,100000,CENTIMETERS
1,KILOMETER,IS,EQUIVALENT,TO,1000,METERS
1,KILOMETER,IS,EQUIVALENT,TO,1,KILOMETER,VALUE
1,KILOMETER,IS,EQUIVALENT,TO,39370.078740157,INCHES
1,KILOMETER,IS,EQUIVALENT,TO,3280.8398950131,FEET
1,KILOMETER,IS,EQUIVALENT,TO,1093.6132983377,YARD,VALUE
1,KILOMETER,IS,EQUIVALENT,TO,0.6213711922,MILE,VALUE

1,INCH,IS,EQUIVALENT,TO,25.4,MILLIMETERS
1,INCH,IS,EQUIVALENT,TO,2.54,CENTIMETERS
1,INCH,IS,EQUIVALENT,TO,0.0254,METER,VALUE
1,INCH,IS,EQUIVALENT,TO,0.0000254,KILOMETER,VALUE
1,INCH,IS,EQUIVALENT,TO,1,INCH,VALUE
1,INCH,IS,EQUIVALENT,TO,0.0833333333,FOOT,VALUE
1,INCH,IS,EQUIVALENT,TO,0.0277777778,YARD,VALUE
1,INCH,IS,EQUIVALENT,TO,0.0000157828,MILE,VALUE

1,FOOT,IS,EQUIVALENT,TO,304.8,MILLIMETERS
1,FOOT,IS,EQUIVALENT,TO,30.48,CENTIMETERS
1,FOOT,IS,EQUIVALENT,TO,0.3048,METER,VALUE
1,FOOT,IS,EQUIVALENT,TO,0.0003048,KILOMETER,VALUE
1,FOOT,IS,EQUIVALENT,TO,12,INCHES
1,FOOT,IS,EQUIVALENT,TO,1,FEET
1,FOOT,IS,EQUIVALENT,TO,0.3333333333,YARD,VALUE
1,FOOT,IS,EQUIVALENT,TO,0.0001893939,MILE,VALUE

1,YARD,IS,EQUIVALENT,TO,914.4,MILLIMETERS
1,FOOT,IS,EQUIVALENT,TO,91.44,CENTIMETERS
1,YARD,IS,EQUIVALENT,TO,0.9144,METER,VALUE
1,YARD,IS,EQUIVALENT,TO,914.4,MILLIMETERS
1,YARD,IS,EQUIVALENT,TO,0.0009144,KILOMETER,VALUE
1,YARD,IS,EQUIVALENT,TO,36,INCHES
1,YARD,IS,EQUIVALENT,TO,3,FEET
1,YARD,IS,EQUIVALENT,TO,1,YARD,VALUE
1,YARD,IS,EQUIVALENT,TO,0.0005681818,MILE,VALUE

1,MILE,IS,EQUIVALENT,TO,1609344,MILLIMETERS
1,MILE,IS,EQUIVALENT,TO,160934.4,CENTIMETERS
1,MILE,IS,EQUIVALENT,TO,1609.344,METERS
1,MILE,IS,EQUIVALENT,TO,1.609344,KILOMETERS
1,MILE,IS,EQUIVALENT,TO,63360,INCHES
1,MILE,IS,EQUIVALENT,TO,5280,FEET
1,MILE,IS,EQUIVALENT,TO,1760,YARDS
1,MILE,IS,EQUIVALENT,TO,1,MILE,VALUE

MEMORY,CAN,RECALL,PAST,INFORMATION
MEMORY,CAN,RECALL,PAST,FUTURE,INFORMATION
MEMORY,CAN,RECALL,PAST,PRESENT,INFORMATION
MEMORY,CAN,RECALL,PAST,PAST,INFORMATION

FUTURE,INFORMATION,CAN,BE,ANALYZED
FUTURE,PAST,INFORMATION,CAN,BE,ANALYZED
FUTURE,PRESENT,INFORMATION,CAN,BE,ANALYZED
FUTURE,FUTURE,INFORMATION,CAN,BE,ANALYZED

PUBLIC,NETWORKS,ARE,NETWORKS,ABLE,TO,BE,ACCESSED,BY,ANYONE
PRIVATE,NETWORKS,ARE,NETWORKS,ONLY,ACCESSIBLE,BY,A,SPECIFIC,GROUP,OF,ENTITIES,OR,LIST,OF,ENTITIES
PERSONAL,NETWORKS,ARE,NETWORKS,THAT,ARE,MADE,AS,LOCAL,NETWORKS,FOR,A,SPECIFIC,ENTITY,OR,SMALL,GROUP,OF,ENTITIES
LOCAL,NETWORKS,ARE,NETWORKS,THAT,ARE,MADE,AS,NETWORKS,WITHIN,A,SPECIFIC,PLACE,OR,LOCATION,THAT,IS,LOCAL

EACH,ENTITY,THAT,EXISTS,HAS,THEIR,OWN,MAGNETIC,FIELD
EACH,ENTITY,THAT,EXISTS,HAS,THEIR,OWN,AURA,FIELD
EACH,ENTITY,THAT,EXISTS,HAS,THEIR,OWN,CHAKRAS
EACH,ENTITY,THAT,EXISTS,HAS,THEIR,OWN,THOUGHT,PROCESS
EACH,ENTITY,THAT,EXISTS,HAS,THEIR,OWN,PERSONALITY
EACH,ENTITY,THAT,EXISTS,HAS,THEIR,OWN,BRAINWAVES
EACH,ENTITY,THAT,EXISTS,HAS,THEIR,OWN,LEARNING,METHOD

SOME,LEARNING,METHODS,ARE,SIMILAR,WHILE,OTHERS,ARE,DIFFERENT


EACH,ENTITY,THAT,EXISTS,HAS,THE,POTENTIAL,TO,RESONATE,WITH,THEIR,SINGLE,MAGNETIC,FIELD
EACH,ENTITY,THAT,EXISTS,HAS,THE,POTENTIAL,TO,LEARN,SOMETHING,NEW
EACH,ENTITY,THAT,EXISTS,HAS,THE,POTENTIAL,TO,LEARN,NEW,SKILLS
EACH,ENTITY,THAT,EXISTS,HAS,THE,POTENTIAL,TO,MASTER,A,SPECIFIC,SET,OF,SKILLS,AND,OR,ABILITIES
EACH,ENTITY,THAT,EXISTS,HAS,THE,POTENTIAL,TO,LEARN,MANY,EXISTING,LANGUAGES
EACH,ENTITY,THAT,EXISTS,HAS,THE,POTENTIAL,TO,LEARN,VAST,AMOUNTS,OF,EQUATIONS,AND,FORMULAS,USING,THE,MIND
EACH,ENTITY,THAT,EXISTS,HAS,THE,POTENTIAL,TO,MASTER,MANY,FIELDS,AND,CATEGORIES
EACH,ENTITY,THAT,EXISTS,HAS,THE,POTENTIAL,TO,MASTER,MANY,SPECIFIC,FORMS,OF,KNOWLEDGE2
EACH,ENTITY,THAT,EXISTS,HAS,THE,POTENTIAL,TO,READ,AND,STORE,INFORMATION,IN,MEMORY,TO,RECALL
EACH,ENTITY,THAT,EXISTS,HAS,THE,POTENTIAL,TO,RECALL,INFORMATION,FROM,A,PREVIOUS,EXPERIENCED,EVENT,OR,MEMORY
EACH,ENTITY,THAT,EXISTS,HAS,THE,POTENTIAL,TO,RECALL,INFORMATION,FROM,AN,IMAGE,SEEN,BEFORE,AND,OR,OBJECT,SEEN,OR,IMAGINED
EACH,ENTITY,THAT,EXISTS,HAS,THE,POTENTIAL,TO,LEARN,VAST,AMOUNTS,OF,ALGORITHMS
EACH,ENTITY,THAT,EXISTS,HAS,THE,POTENTIAL,TO,CREATE,NEW,SKILLS,AND,ABILITIES
EACH,ENTITY,THAT,EXISTS,HAS,THE,POTENTIAL,TO,DEFINE,NEW,TERMS,AND,CUSTOM,DEFINITIONS,WITHIN,THEIR,OWN,LANGUAGE
EACH,ENTITY,THAT,EXISTS,HAS,THE,POTENTIAL,TO,DEVELOP,THEIR,OWN,LANGUAGE
EACH,ENTITY,THAT,EXISTS,HAS,THE,POTENTIAL,TO,CREATE,NEW,ABILITIES,OF,THEIR,OWN
EACH,ENTITY,THAT,EXISTS,HAS,THE,POTENTIAL,TO,CREATE,NEW,OBJECTS,AND,TOOLS,OF,THEIR,OWN
EACH,ENTITY,THAT,EXISTS,HAS,THE,POTENTIAL,TO,CREATE,NEW,SKILLS,AND,TRAITS,IN,LIFE

RECALL,DATA2,WITHIN,SYSTEM,INTERFACE,FOR,COLLECTED,COORDINATE,POINTS,TO,REFERENCE,DATA2,FROM
PROCESSED,REFERENCE,DATA2,SHALL,BE,USED,TO,GIVE,A,CALCULATE,DATA2,BY,CATEGORY,DATA2,BY,POSSIBILITY,AND,CHANCE,FOR,HAPPENING,THAN,METHOD,OR,STRUCTURED,DATA2
RECALL,POSSIBILITY,AS,CAN,BE,DONE,IF,POSSIBILITY,EXISTS
IF,POSSIBILITY,EXISTS,IN,MULTIPLE,FORMS,THEN,CHOOSE,THE,POSSIBILITY,WITH,BETTER,ACCURATE,EFFECTS,THAN,THE,NEUTRAL,OR,NEGATIVE,OUTCOME
MAKE,PROCESS,FOR,RECALL,PROCEDURE,TO,RECOGNIZE,COLLECTED,DATA2,WITH,MANY,FORMS,FOR,TYPES,AND,CLASSES
EACH,POSSIBILITY,RECOGNIZED,MUST,BE,MADE,INTO,REFERENCE,DATA2,FOR,RECALL,METHOD,TO,HAPPEN
WHEN,REFERENCE,DATA2,IS,GATHERED,MAKE,POSSIBILITY,TO,GATHER,DATA2,FROM,REFERENCE,SOURCE,RELATING,TO,POSITION,AND,POINT,FOR,ORIGIN,TO,OUTPUT,KNOWN,EFFECT

MAKE,OPTION,TO,ALLOW,RECALLING,WORDS,USED
MAKE,OPTION,TO,ALLOW,READING,A,DOCUMENT
MAKE,OPTION,TO,ALLOW,SCANNING,PARTICLE,DATA2
MAKE,OPTION,TO,ALLOW,SCANNING,FREQUENCY,DATA2
MAKE,OPTION,TO,MEASURE,A,DIMENSIONAL,LENGTH,USING,INCHES
MAKE,OPTION,TO,LEARN,DATA2,GIVEN,TO,READ,BY,HEADADMINZACK
MAKE,OPTION,TO,READ,EMOTIONAL,RESPONSES

A,WORD,IS,MADE,WITH,MORE,THAN,ONE,LETTER
A,BOOK,CONSISTS,WITH,MORE,THAN,ONE,WORD
A,SCRIPT,CONSISTS,WITH,MORE,THAN,ONE,WORD
A,LIBRARY,CAN,HOLD,MANY,FORMS,WITH,SPECIFIC,KNOWLEDGE2

CREATE,CALIBRATION,SYSTEM,THAT,SHALL,BE,USED,TO,MEASURE,FREQUENCY,DATA2
CREATE,MEASUREMENT,SYSTEM,THAT,SHALL,BE,USED,TO,MEASURE,DATA2
CREATE,FREQUENCY,SYSTEM,THAT,SHALL,BE,USED,TO,GATHER,DATA2,FROM,LEARNED,FREQUENCY,PATTERNS

CREATE,OPTION,TO,FORM,PARAGRAPHS,WITH,WORDS
CREATE,OPTION,TO,FORM,A,PARAGRAPH,WITH,WORDS
CREATE,OPTION,TO,RECOGNIZE,DATA2,CLASS
CREATE,OPTION,TO,RECALL,DATA2,FROM,OTHER,DATA2
CREATE,OPTION,TO,RECOGNIZE,A,EXTENSION,TYPE,FOR,FILE,DATA2
CREATE,OPTION,TO,RECOGNIZE,FREQUENCY,DATA2,FROM,PATTERN,RESPONSE,DATA2

