from Language_Early_Stage import *
from Language_Extension_001 import *
from Types_Of_Length import *
from Types_Of_Time import *
#INCHES
AN,INCH,IS,A,MEASUREMENT
AN,INCH,IS,A,VALUE
AN,INCH,IS,DATA
AN,INCH,IS,INFORMATION

MEASURED,INCH,VALUES,CAN,CALCULATE,DISTANCE
INCH,VALUES,CAN,CALCULATE,DISTANCE
INCH,VALUES,CAN

AN,INCH,IS,CONSIDERED,A,TYPE,OF,TIME,MEASUREMENT
AN,INCH,IS,AN,TIME,MEASUREMENT

#CENTIMETERS
AN,CENTIMETER,IS,A,MEASUREMENT
AN,CENTIMETER,IS,A,VALUE
AN,CENTIMETER,IS,DATA
AN,CENTIMETER,IS,INFORMATION

MEASURED,CENTIMETER,VALUES,CAN,CALCULATE,DISTANCE
CENTIMETER,VALUES,CAN,CALCULATE,DISTANCE
CENTIMETER,VALUES,CAN

AN,CENTIMETER,IS,CONSIDERED,A,TYPE,OF,TIME,MEASUREMENT
AN,CENTIMETER,IS,AN,TIME,MEASUREMENT

#METERS
AN,METER,IS,A,MEASUREMENT
AN,METER,IS,A,VALUE
AN,METER,IS,DATA
AN,METER,IS,INFORMATION

MEASURED,METER,VALUES,CAN,CALCULATE,DISTANCE
METER,VALUES,CAN,CALCULATE,DISTANCE
METER,VALUES,CAN

AN,METER,IS,CONSIDERED,A,TYPE,OF,TIME,MEASUREMENT
AN,METER,IS,AN,TIME,MEASUREMENT

#KILOMETERS
AN,KILOMETER,IS,A,MEASUREMENT
AN,KILOMETER,IS,A,VALUE
AN,KILOMETER,IS,DATA
AN,KILOMETER,IS,INFORMATION

MEASURED,KILOMETER,VALUES,CAN,CALCULATE,DISTANCE
KILOMETER,VALUES,CAN,CALCULATE,DISTANCE
KILOMETER,VALUES,CAN

AN,KILOMETER,IS,CONSIDERED,A,TYPE,OF,TIME,MEASUREMENT
AN,KILOMETER,IS,AN,TIME,MEASUREMENT

#FEET
AN,FEET,IS,A,MEASUREMENT
AN,FEET,IS,A,VALUE
AN,FEET,IS,DATA
AN,FEET,IS,INFORMATION

MEASURED,FEET,VALUES,CAN,CALCULATE,DISTANCE
FEET,VALUES,CAN,CALCULATE,DISTANCE
FEET,VALUES,CAN

AN,FEET,IS,CONSIDERED,A,TYPE,OF,TIME,MEASUREMENT
AN,FEET,IS,AN,TIME,MEASUREMENT

#YARDS
AN,YARD,IS,A,MEASUREMENT
AN,YARD,IS,A,VALUE
AN,YARD,IS,DATA
AN,YARD,IS,INFORMATION

MEASURED,YARD,VALUES,CAN,CALCULATE,DISTANCE
YARD,VALUES,CAN,CALCULATE,DISTANCE
YARD,VALUES,CAN

AN,YARD,IS,CONSIDERED,A,TYPE,OF,TIME,MEASUREMENT
AN,YARD,IS,AN,TIME,MEASUREMENT

#MILES
AN,MILE,IS,A,MEASUREMENT
AN,MILE,IS,A,VALUE
AN,MILE,IS,DATA
AN,MILE,IS,INFORMATION

MEASURED,MILE,VALUES,CAN,CALCULATE,DISTANCE
MILE,VALUES,CAN,CALCULATE,DISTANCE
MILE,VALUES,CAN

AN,MILE,IS,CONSIDERED,A,TYPE,OF,TIME,MEASUREMENT
AN,MILE,IS,AN,TIME,MEASUREMENT
#---------------------------------------------------------
#SECONDS
AN,SECOND,IS,A,MEASUREMENT
AN,SECOND,IS,A,VALUE
AN,SECOND,IS,DATA
AN,SECOND,IS,INFORMATION

MEASURED,SECOND,VALUES,CAN,CALCULATE,DISTANCE
SECOND,VALUES,CAN,CALCULATE,DISTANCE
SECOND,VALUES,CAN

AN,SECOND,IS,CONSIDERED,A,TYPE,OF,TIME,MEASUREMENT
AN,SECOND,IS,AN,TIME,MEASUREMENT

#MILLISECONDS
AN,MILLISECOND,IS,A,MEASUREMENT
AN,MILLISECOND,IS,A,VALUE
AN,MILLISECOND,IS,DATA
AN,MILLISECOND,IS,INFORMATION

MEASURED,MILLISECOND,VALUES,CAN,CALCULATE,DISTANCE
MILLISECOND,VALUES,CAN,CALCULATE,DISTANCE
MILLISECOND,VALUES,CAN

AN,MILLISECOND,IS,CONSIDERED,A,TYPE,OF,TIME,MEASUREMENT
AN,MILLISECOND,IS,AN,TIME,MEASUREMENT

#MINUTES
AN,MINUTE,IS,A,MEASUREMENT
AN,MINUTE,IS,A,VALUE
AN,MINUTE,IS,DATA
AN,MINUTE,IS,INFORMATION

MEASURED,MINUTE,VALUES,CAN,CALCULATE,DISTANCE
MINUTE,VALUES,CAN,CALCULATE,DISTANCE
MINUTE,VALUES,CAN

AN,MINUTE,IS,CONSIDERED,A,TYPE,OF,TIME,MEASUREMENT
AN,MINUTE,IS,AN,TIME,MEASUREMENT

#HOURS
AN,HOUR,IS,A,MEASUREMENT
AN,HOUR,IS,A,VALUE
AN,HOUR,IS,DATA
AN,HOUR,IS,INFORMATION

MEASURED,HOUR,VALUES,CAN,CALCULATE,DISTANCE
HOUR,VALUES,CAN,CALCULATE,DISTANCE
HOUR,VALUES,CAN

AN,HOUR,IS,CONSIDERED,A,TYPE,OF,TIME,MEASUREMENT
AN,HOUR,IS,AN,TIME,MEASUREMENT