from Language_Early_Stage import *
RECALL,DATA,WITHIN,SYSTEM,INTERFACE,FOR,COLLECTED,COORDINATE,POINTS,TO,REFERENCE,DATA,FROM
PROCESSED,REFERENCE,DATA,SHALL,BE,USED,TO,GIVE,A,CALCULATE,DATA,BY,CATEGORY,DATA,BY,POSSIBILITY,AND,CHANCE,FOR,HAPPENING,THAN,METHOD,OR,STRUCTURED,DATA
RECALL,POSSIBILITY,AS,CAN,BE,DONE,IF,POSSIBILITY,EXISTS