
from Language_Early_Stage import *
from Language_Extension_001 import *
from Creature_Stats import *
from Types_Of_Seasons import *
from Time_Of_Day import *
from Types_Of_Time import *
from Habitat_Dex_Data import * 
["_CREATURENAME_"],HAS,A,ATTACKSTAT,OF,80

["_CREATURENAME_"],HAS,A,DEFENSESTAT,OF,70

["_CREATURENAME_"],HAS,A,SPECIALDEFENSESTAT,OF,90

["_CREATURENAME_"],HAS,A,SPECIALATTACKSTAT,OF,70

["_CREATURENAME_"],HAS,A,SPEEDSTAT,OF,110

["_CREATURENAME_"],HAS,THE,ABILITY,["_ABILITYNAME_"]

THE,TECHNIQUE,["_MOVENAME_"],EXISTS,WITHIN,["_CREATURENAME_"],LIST,OF,KNOWN,TECHNIQUES

["_MOVENAME_"],SHALL,ACTIVATE,A,"SANDSTORM",FOR,TWO,MINUTES

APPROVE,THE,TECHNIQUE,["_MOVENAME_"],EXISTS,WITHIN,["_CREATURENAME_"],LIST,OF,KNOWN,TECHNIQUES,POSSIBILITY,OBTAIN,TECHNIQUE,["_MOVENAME_"],UPON,AT2,LEVEL,5

["_CREATURENAME_"],CAN,BE,FOUND,WITH,LEVELS,BETWEEN,LEVEL,2,TO,LEVEL,5

ROUTE,211,HAS,A,.20,CHANCE,TO,FIND,["_CREATURENAME_"],INSIDE,SHORT_GRASS,DURING,DAYTIME,WHILE,THE,"SEASON",IS,SPRING

THE,HIGHEST,LEVEL,["_CREATURENAME_"],CAN,REACH,IS,LEVEL,100

THE,LOWEST,LEVEL,["_CREATURENAME_"],CAN,REACH,IS,LEVEL,1
