from Language_Early_Stage import *
CREATE,CALIBRATION,SYSTEM,THAT,SHALL,BE,USED,TO,MEASURE,FREQUENCY,DATA
CREATE,MEASUREMENT,SYSTEM,THAT,SHALL,BE,USED,TO,MEASURE,DATA
CREATE,FREQUENCY,SYSTEM,THAT,SHALL,BE,USED,TO,GATHER,DATA,FROM,LEARNED,FREQUENCY,PATTERNS