from Language_Early_Stage import *
CREATE,OPTION,TO,FORM,PARAGRAPHS,WITH,WORDS
CREATE,OPTION,TO,FORM,A,PARAGRAPH,WITH,WORDS
CREATE,OPTION,TO,RECOGNIZE,DATA,CLASS
CREATE,OPTION,TO,RECALL,DATA,FROM,OTHER,DATA
CREATE,OPTION,TO,RECOGNIZE,A,EXTENSION,TYPE,FOR,FILE,DATA
CREATE,OPTION,TO,RECOGNIZE,FREQUENCY,DATA,FROM,PATTERN,RESPONSE,DATA
