from Language_Early_Stage import *
MAKE,OPTION,TO,ALLOW,RECALLING,WORDS,USED
MAKE,OPTION,TO,ALLOW,READING,A,DOCUMENT
MAKE,OPTION,TO,ALLOW,SCANNING,PARTICLE,DATA
MAKE,OPTION,TO,ALLOW,SCANNING,FREQUENCY,DATA
MAKE,OPTION,TO,MEASURE,A,DIMENSIONAL,LENGTH
MAKE,OPTION,TO,LEARN,DATA,GIVEN,TO,READ,BY,HEADADMINZACK
MAKE,OPTION,TO,READ,EMOTIONAL,RESPONSES

A,WORD,IS,MADE,FOR,MORE,THAN,ONE,LETTER
A,BOOK,CONSISTS,FOR,MORE,THAN,ONE,WORD
A,SCRIPT,CONSISTS,FOR,MORE,THAN,ONE,WORD
A,LIBRARY,CAN,HOLD,MANY,FORMS,FOR,SPECIFIC,KNOWLEDGE
