from Language_Early_Stage import *
from Numbers_One_To_OneThousand import *
from Language_Extension_001 import *
from Types_Of_Calendar_Time import *
FIVE,DAY,VALUES,IS,EQUIVALENT,TO,ONE,WEEK,VALUE
ONE,WEEK,VALUE,IS,EQUIVALENT,TO,FIVE,DAY,VALUES
THREEHUNDREDSIXTYFIVE,DAY,VALUES,IS,EQUIVALENT,TO,ONE,YEAR,VALUE
ONE,YEAR,VALUE,IS,EQUIVALENT,TO,THREEHUNDREDSIXTYFIVE,DAY,VALUES
