CREATE NEW CLASS:
    NEW CLASS SHALL BE GIVEN NAME "STATES_OF_CONSCIOUSNESS.CLASSES";
        CLASS SHALL CONTAIN THE NAME FOR FIVE DIFFERENT TYPES FOR THE EXISTING STATES OF CONSCIOUSNESS
        TYPE ONE IS THE "CONSCIOUSNESS"
        TYPE TWO IS THE "UNCONSCIOUSNESS"
        TYPE THREE IS THE "NONCONSCIOUSNESS"
        TYPE FOUR IS THE "SUBCONCSCIOUSNESS"
        TYPE FIVE IS THE "SUPERCONSCIOUSNESS"
    END CLASS:
END COMMAND: