CREATE NEW CLASS:
    NEW CLASS SHALL BE GIVEN NAME "EYESIGHT.CLASSES";
        CLASS SHALL CONTAIN THE NAME FOR TWO DIFFERENT TYPES FOR EYESIGHT
        TYPE ONE IS AN "NEAR-SIGHTED" EYESIGHT
        TYPE TWO IS AN "FAR-SIGHTED" EYESIGHT
    END CLASS:
END COMMAND: