from Language_Early_Stage import *
CREATE,NEW,CLASS
NEW,CLASS,SHALL,BE,GIVEN,NAME,"WAVELENGTH.CLASSES"
CLASS,SHALL,CONTAIN,THE,DATA,USED,TO,GATHER,INFORMATION,FROM,WAVELENGTH,DATA
DATA,SHALL,BE,GATHERED,FROM,THE,BEGINNING,LOCATION,FOR,A,WAVELENGTH
DATA,SHALL,BE,GATHERED,FROM,THE,DESTINATION,LOCATION,FOR,A,WAVELENGTH
DATA,SHALL,BE,GATHERED,FROM,THE,FREQUENCY,INFORMATION,GATHERED,FROM,WITHIN,THE,WAVELENGTH
DATA,SHALL,BE,GATHERED,ON,THE,NUMBER,FOR,CYCLES,A,WAVELENGTH,HAS
DATA,SHALL,BE,GATHERED,ON,THE,HERTZ,FOR,A,WAVELENGTH
DATA,SHALL,BE,GATHERED,ON,THE,LENGTH,FOR,A,WAVELENGTH
DATA,SHALL,BE,GATHERED,ON,THE,HEIGHT,FOR,A,WAVELENGTH
