from Language_Early_Stage import *
CREATE,CLASS,FOR,IF,STATEMENT,MANAGER,SETTINGS,FOR,MANAGING,FLOW,FOR,MEMORY,FOR,USED,IF,STATEMENT,FOR,PAST,RECALL
EACH,IF,STATEMENT,SHALL,BE,USED,TO,RECALL,PREVIOUS,FORMS,FOR,INFORMATION,WITHIN,DATA
IF,EACH,FORM,FOR,IF,STATEMENT,IS,ABLE,TO,GAIN,ACCESS,TO,A,PREVIOUS,TERM
CHECK,IF,STATEMENT,IS,A,FORM,FOR,COMMAND,AND,NOT,A,CATEGORY,REFERENCE
IF,STATEMENT,IS,A,CATEGORY,FOR,REFERENCE
THEN,DISPLAY,CATEGORY
ELSE,DISPLAY,PREVIOUS,TERM,ACCESSED
