from Language_Early_Stage import *
CREATE,NEW,CLASS
NEW,CLASS,SHALL,BE,GIVEN,NAME,"UNIT.TYPES"
DATA,FORMED,FROM,UNIT,TYPES,HAVE,A,SPECIFIC,FORM,FOR,INFORMATION,THAT,HAS,THE,INFORMATION,FOR,THE,UNIT,SIZE,AND,UNIT,LEVEL,FOR,THAT,SPECIFIC,UNIT,TYPE
DATA,ANALYZED,AND,CONSIDERED,DATA,FOR,A,UNIT,TYPE,SHALL,HAVE,A,METHOD,FORMED,TO,CALCULATE,UNIT,SIZE
EACH,FORM,FOR,DATA,MEASURED,SHALL,HOLD,A,SPECIFIC,AMOUNT,FOR,DATA,TO,ANSWER,DATA,SIZE,LEVEL,AT,A,FUTURE,DATE