from Language_Early_Stage import *
from Types_Of_Wavelengths import *
CREATE,NEW,CLASS
NEW,CLASS,SHALL,BE,GIVEN,NAME,"FREQUENCY.CLASSES"
CLASS,SHALL,CONTAIN,THE,NAME,FOR,FIVE,DIFFERENT,TYPES,FOR,FREQUENCIES
TYPE,ONE,IS,AN,ALPHA,WAVELENGTH
TYPE,TWO,IS,AN,BETA,WAVELENGTH
TYPE,THREE,IS,AN,THETA,WAVELENGTH
TYPE,FOUR,IS,AN,DELTA,WAVELENGTH