from Language_Early_Stage import *
CREATE,NEW,COMMAND,PROMPT
SET,NEW,COMMAND,TO,GATHER,DATA,FROM,A,PARAMETER,WHEN,REQUEST,HAS,BEEN,MADE
EACH,FORM,FOR,DATA,SHALL,BE,GIVEN,A,CATEGORY,LOCATION,TO,FORM,OUTPUT,TO,GIVING,EACH,TYPE,FOR,DATA,A,LOCATION,TO,BE,STORED,WITH,A,CATEGORY,NAME
