from Language_Early_Stage import *
FANTASY = "A GENRE OF A BOOK THAT USES COMPLETE FREEDOM OF IMAGINATION AND CREATIVITY WITH POSSIBILITY OF MAGIC TO EXIST WITHIN THE REALM ITSELF"
SCIENCE_FICTION = "A GENRE OF A BOOK THAT USES MANY PHYSICAL FORMS OF A DEVICE AND GADGET TO DEVELOP A DESCRIPTION"
ROMANCE = "A GENRE OF A BOOK THAT DEFINES THE DEFINITION OF TWO ENTITIES DEVELOPING A CONNECTION TOGETHER AND FORMING A HARMONY WITHIN EACH OTHER AS TWO ATTRACTED ENTITIES WITH LOVE AND FAITH AND BELIEF WITH EACH OTHER WITHIN AN INTERVAL OF TIME"
ADVENTURE = "A GENRE OF A BOOK THAT CONTAINS MANY TIMEFRAME POINTS WITH THE DEVELOPMENT OF A SPECIFIC CHARACTER COMPLETE MANY DIFFERENT SIZED TASKS IN ORDER TO ACHIEVE ONE MAIN GOAL OR ACHIEVEMENT BY THE END OF THE BOOK"
