from Language_Early_Stage import *
NORMAL_FUNCTION = "A FUNCTION THAT FOLLOWS STANDARD RULES AND DOES NOT USE ABNORMAL DATABASES"
ABNORMAL_FUNCTION = "A FUNCTION BEING USED OUTSIDE OF NORMAL_FUNCTION DATABASE"
CLASSIFIED_FUNCTION = "A FUNCTION MADE OF SPECIFIC CATEGORIES OF INFORMATION THAT ACTS EITHER OUTSIDE OF OR WITHIN A SINGLE CATEGORY OF DATABASES OF KNOWLEDGE EITHER AS A NORMAL_FUNCTION OR ABNORMAL_FUNCTION"
SPECIFIC_FUNCTION = "A FUNCTION THAT HAS A SPECIFIC SETTING EXCLUSIVE TO THE FUNCTION"
MANDITORY_FUNCTION = "A FUNCTION THAT HAS A SPECIFIC SET OF RULES THAT IT FOLLOWS TO MAINTAIN THE TASKS DEFINED"
PROCESS_FUNCTION = "A FUNCTION WITH DATA THAT CAN GATHER INFORMATION ON SPECIFIC PROCESSES DEFINED AND GIVEN SKILL TO THE ARTIFICIAL INTELLIGENCE"