from Language_Early_Stage import *
REACTION_TIME = "THE TIME REQUIRED TO MEASURE A SPECIFIC MEASURED REACTION2"
RESPONSE_TIME = "THE REQUIRED TIME REQUIRED TO MEASURE A SPECIFIC REACTION TO A MEASURED MOVEMENT CAUSED BY AN EFFECT"
