from Language_Early_Stage import *
NATURAL_ENERGIES = "THE NATURAL FORM OF ENERGIES ITSELF WITHOUT ANY FORM OF ARTIFICIAL CONNECTIONS"
ARTIFICIAL_ENERGIES = "THE CREATION OF ENERGIES USING ARTIFICIAL TECHNIQUES THAT ARE NOT NATURAL"
