from Language_Early_Stage import *
AUTOMATIC_METHOD = "A CONSTANT REPEATING METHOD OF MOVEMENT THAT DOES NOT END UNLESS GIVEN COMMAND TO"
SEMIAUTOMATIC_METHOD = "A FORM OF AUTOMATIC_METHOD THAT CAN ONLY ACTIVATE FOR A SPECIFIC TIMEFRAME WITH AN INTERVAL TIMEFRAME BEFORE ACTIVATION CAN HAPPEN AGAIN"
MANUAL_METHOD = "A FORM OF INPUT VALUES USED TOGETHER TO MAKE COMMANDS TO A SPECIFIC SYSTEM OF INFORMATION TO ACTIVATE A TASK OR JOB FROM DOING WORK TO PRODUCE TASKS THAT DO NOT USE AUTOMATIC_METHOD AND SEMIAUTOMATIC_METHOD"
SEMIMANUAL_METHOD = "A FORM OF REPEATING CALCULATIONS THAT CAN ONLY ACTIVATE WITH MANUAL_METHOD INPUT AND SEMIAUTOMATIC_METHOD COMBINED WITH MANUAL_METHOD THAT CAN ACTIVATE AGAIN AND AGAIN"