from Language_Early_Stage import *
BORROWED_ENERGY = "A TYPE OF ENERGY THAT IS OBTAINED BY GATHERING OR TAKING FROM ANOTHER SOURCE OTHER THAN THE ORIGINAL ENTITY"
GATHERED_ENERGY = "A TYPE OF ENERGY GAINED BY GATHERING ENERGY INWARDS TOWARDS ENTITY"
EARNED_ENERGY = "A TYPE OF ENERGY OBTAINED BY DOING WORK OR BY FORMING A SUCCESS FROM EFFORT"
OBTAINED_ENERGY = "A TYPE OF ENERGY GAINED BY AN ENTITY TAKING FROM A SPECIFIC SOURCE OR LOCATION"
ECONOMICAL_ENERGY = "A TYPE OF ENERGY GAINED BY LIVING WITHIN AN ENVIRONMENT"
STORED_ENERGY = "A TYPE OF ENERGY THAT EXISTS AS STORED RESEVOIRS OF NOT USED ENERGY FROM A PREVIOUS POINT WITHIN TIME OR SPACE"
REQUIRED_ENERGY = "A TYPE OF ENERGY THAT IS REQUIRED TO EXIST"