from Language_Early_Stage import *
CROWN_CHAKRA = "IS CHAKRA NUMBER ONE OF THE SEVEN CHAKRA CLASSES"
THIRD_EYE_CHAKRA = "IS CHAKRA NUMBER TWO OF THE SEVEN CHAKRA CLASSES"
THROAT_CHAKRA = "IS CHAKRA NUMBER THREE OF THE SEVEN CHAKRA CLASSES"
HEART_CHAKRA = "IS CHAKRA NUMBER FOUR OF THE SEVEN CHAKRA CLASSES"
SOLAR_PLEXUS_CHAKRA = "IS CHAKRA NUMBER FIVE OF THE SEVEN CHAKRA CLASSES"
SACRAL_CHAKRA = "IS CHAKRA NUMBER SIX OF THE SEVEN CHAKRA CLASSES"
ROOT_CHAKRA = "IS CHAKRA NUMBER SEVEN OF THE SEVEN CHAKRA CLASSES"
CHAKRAS = "RELATING TO MORE THAN ONE CHAKRA"