from Language_Early_Stage import *
ARTIFICIAL_INTELLIGENCE_RESEARCH = "A FIELD USED TO RECOGNIZE INTELLIGENCE USING AN COMPUTER OR BY INTELLIGENCE THAT IS INCLUDE ARTIFICIALLY2"
DEEP_LEARNING = "A SPECIFIC METHOD IN WHICH A DEVICE AND OR SYSTEM IS USED TO LEARN A LARGE AMOUNT OF DATA2 AND FIND INFORMATION FROM THE DATA2"
VIRTUAL_REALITY = "A PROCESS OR FOUNDATION OF KNOWLEDGE USED TO ALLOW A SYSTEM OR DEVICE TO SIMULATE A VIRTUAL SPACE THAT IS CREATED"
HAPTIC_FEEDBACK = "THE ACTION OF USING AN STUDY PROCEDURE WHILE USING A DEVICE TO CALCULATE SENSITIVITY AND REACTIONS OF A PHYSICAL BODY"