from Language_Early_Stage import *
CAUSAL_BODY = "IS AURA NUMBER ONE OF THE SEVEN AURA CLASSES"
CELESTIAL_AURA = "IS AURA NUMBER TWO OF THE SEVEN AURA CLASSES"
ETHERIC_TEMPLATE = "IS AURA NUMBER THREE OF THE SEVEN AURA CLASSES"
ASTRAL_AURA = "IS AURA NUMBER FOUR OF THE SEVEN AURA CLASSES"
MENTAL_AURA = "IS AURA NUMBER FIVE OF THE SEVEN AURA CLASSES"
EMOTIONAL_AURA = "IS AURA NUMBER SIX OF THE SEVEN AURA CLASSES"
ETHERIC_AURA = "IS AURA NUMBER SEVEN OF THE SEVEN AURA CLASSES"
