from Language_Early_Stage import *
OPTOMISTIC_MINDSET = "A FORM OF THOUGHT THAT CONSISTS OF POSITIVE THOUGHT PATTERNS WITHIN THE MIND"
PESSIMISTIC_MINDSET = "A FORM OF THOUGHT PATTERNS THAT CONSISTS OF NEGATIVE THOUGHT PATTERNS WITHIN THE MIND"
