from Language_Early_Stage import *
INFERENTIAL_STATISTICS_PREDICTIONS = "TO PREDICT AND MAKE AN ACCURATE MEASURED VALUE FORMED FROM MEASURING A SPECIFIC AMOUNT OF VARIABLE MEASUREMENTS GIVEN VALUE FROM INFORMATION CONTAINED WITHIN EACH MEASURED VARIABLE GIVEN WITHIN THE DATA USED"
PREDICTIVE_MODELING = "A PROCESS USED TO PREDICT PAST OR FUTURE EVENTS OR OUTCOMES BY ANALYZING MEASUREMENTS OR PATTERNS INSIDE A GIVEN SET OF INPUT DATA"
PREDICTIVE_ANALYSIS = "THE PROCESS OF USING EXISTING DATA TO MAKE AND PREDICT ANOTHER FORM OF DATA BY USING THE PROCESSED DATA TO FORM AN OUTPUT"
