from Language_Early_Stage import *


RECALL = "GAIN THE ABILITY TO VIEW PAST MEMORY INSIDE BRAIN"
RECOGNIZE = "RECALL FROM AN EARLIER POINT WITHIN TIME"
MEMORIZE = "OBTAIN AND BALANCE OUTCOME FOR MEMORY CONTAINMENT WHILE SUSTAIN THE ENERGY OF EXISTENCE INSIDE KNOWN REALITY AND REALM"


READ = "DESCRIBE FROM LOOKING AT A PATH OF WORDS"
SCAN = "ANALYZE A SPECIFIC WORD OR FIELD AND OR GIVE DATA ON THE ASKED INFORMATION TO SEARCH FOR"
ANALYZE = "READ AND LOOK OVER"


INTERFACE = "LINKED CONNECTION BETWEEN TWO DESCRIBED SOURCES"
SYSTEM = "SET INTERFACE OF COLLABORATED AND COMPILED SETTINGS"
CONNECTION = "TO BIND BETWEEN TWO SET COORDINATES"
PATH = "GIVEN OR STATED DESTINATION"
DIRECTORY = "SPECIFIC LOCATION OF A FILE OR CONTAINER"


FILE = "TYPE OF DOCUMENT"
FOLDER = "CONTAINER FOR FILES DEPENDANT ON TYPE OF STORAGE TYPE"
DIRECTORY = "SPECIFIC LOCATION OF A FILE OR CONTAINER"
EXTENSION = "AN OPTIONAL ADDED DEFINITION THAT GIVES A PROLONGED MEANING"
LOCATION = "SPECIFIED AREA"
PATH = "GIVEN OR STATED DESTINATION"


UPLOAD = "TRANSFER3 INTO DESCRIBED LOCATION"
DOWNLOAD = "TRANSFER3 TO CURRENT DEVICE"
SIDELOAD = "TRANSFER3 TO ALL DEVICES WITH STATUS OF STATED SET LOCATION"


IMPORT = "BRING IN"
EXPORT = "SEND OUT"
INTORT = "TWIST INWARDS"
EXTORT = "TWIST OUTWARDS"
INTERIOR = "INSIDE LOCATION"
EXTERIOR = "OUTSIDE LOCATION"
INTERNAL = "INNER"
EXTERNAL = "OUTER"
INPUT = "INSERT TO"
OUTPUT = "REMOVE FROM"


ENCODE = "COMPRESS CODE"
DECODE = "DECOMPRESS CODE"
RECODE = "COMPRESS CODE ONCE MORE"
ENCRYPT = "MAKE INFORMATION SECRET"
DECRYPT = "REMOVE A ENCRYPTION"
UNENCRYPT = "REMOVE AN ENCRYPTION"
REENCRYPT = "REDO AN ENCRYPTION"

LOCAL = "LOCATED AROUND A SPECIFIED AREA"

PUBLIC = "ACCESS TO ALL OF CREATORS INTERIOR DOMINION"
PRIVATE = "HIDDEN TO EVERYONE BUT CURRENT2 USER2"
PERSONAL = "EXCLUSIVE TO THE CREATOR"

LETTER = "VARIABLE CONSTRAINED WITH FIELDS OF DATA INFORMATION THAT ACTS OUT AS A COMMANDED TASK"
SYMBOLE = "A GIVES VALUE OF ENERGY BUILT INTO A WORD OF A LANGUAGE BY USING ELECTRON ENERGY WITH COMMAND VALUE WHILE MANIPULATING THE LIFE AND DEATH RATE OF AN ATOM AND GIVES VALUE OF AN OBJECT THE POWER TO MANIPULATE AND TRANSFER PERCIEVED IMAGINARY VALUES INTO STATED VALUE INSIDE EXISTENCE"
DIGIT = "VIRTUAL NUMBER USING WITH EXISTENCE2"
WORD = "WRITTEN AND OR SPOKEN ORDER OR COMMAND"
CODE = "SINGLE DIGITAL WORD"

SENTENCE = "STARTING MIDDLE AND ENDING PATH OF CREATED OR IN USE WORDS"
PARAGRAPH = "MORE THAN ONE SENTENCE THAT GOES UP TO SEVEN LINES AND MAKES A PARABREAK"
PARABREAK = "ENDING CUT OFF BETWEEN ONE PARAGRAPH AND ANOTHER PARAGRAPH"
PAGE = "SCRIPT"
SCRIPT = "A SINGLE STORAGE PAGE OF CODE"
DOCUMENT = "SET PAGE OF LINKED OF PAGES INFORMATION"
BOOK = "A SPECIFIED STORAGE CONTAINER IN PAGES OF SCRIPTS FOR ONE DESIGNATED PLACE OF KNOWLEDGE"
LIBRARY = "STORAGE FOR LANGUAGES AND OR BOOKS"

CATEGORY = "TYPE OF GENRE THAT IS A SUBCLASS"
CATALOGUE = "GENRE OF COLLECTED INFORMATION AND DATA"
GENRE = "A SPECIFIED CLASS THAT HOLDS A LIST OF CATEGORIES"
LIST = "A NUMBER OF CONNECTED OBJECTS OR NAMES AS AN INVENTORY"
CLASS = "FORM OF GENRE THAT IS ABLE TO HAVE MULTIPLE TYPES TO IT"
SUBCLASS = "A SINGLE CLASS UNDER A CLASS"

TYPE = "CATEGORY OR GENRE"
SUBTYPE = "A SINGLE TYPE UNDER A TYPE"

LOCATE = "SEARCH AND SCAN FOR"
LOOK = "SEARCH"
FIND = "LOCATE"
SEARCH = "FIND AND LOCATE SOMETHING"
SCAN = "ANALYZE A SPECIFIC WORD OR FIELD AND OR GIVE DATA ON THE ASKED INFORMATION TO SEARCH FOR"
ANALYZE = "READ AND LOOK OVER"

NUMBER = "ARITHMETICAL VALUE THAT IS EXPRESSED BY A WORD AND OR SYMBOLE AND OR FIGURE REPRESENTING A PARTICULAR QUANTITY AND USED IN COUNTING AND MAKING CALCULATIONS AND OR FOR SHOWING ORDER IN A SERIES OR FOR IDENTIFICATION"
LETTER = "VARIABLE CONSTRAINED WITH FIELDS OF DATA INFORMATION THAT ACTS OUT AS A COMMANDED TASK"
FORMULA = "A STATED CALCULATION OF MULTIPLE OF A VARIABLE THAT CAN TO FORM ALGORITHM OF STATEMENT VALUES FROM MULTIPLE GENERATED SYSTEMS OF VALUES CREATED ALREADY IN PREVIOUS OUTCOME EFFECTS OF LIFE VALUES INSIDE THE EQUATION OF TIME ITSELF AND VERY EXISTENCE AS A POSSIBLE VALUE OF TIME"
EQUATION = "A FORMED CALCULATION MADE BY COMBINING VARIABLES FORMED FROM A COMPLETE LIST OF DEFINED SYMBOLES OR OTHER BASE MEASUREMENTS"
VARIABLE = "VALUE THAT CAN CHANGE AND OR DEPENDING ON CONDITIONS AND OR ON INFORMATION PASSED TO THE PROGRAM"

DEFINITION = "DETERMINE AND OR EXPLAIN"
DESCRIPTION = "SET DIGITAL DEFINITION FOR A WORD"

QUESTION = "ASK SOMETHING NOT KNOWN"
STATEMENT = "COMMAND"
DECLARATION = "COMMANDS TO GIVE ORDERS AS A COMMON VALUE OF STATED AMOUNT STRUCTURE"

FREQUENCY = "REPEATED PATTERN AND OR SETTING"
WAVE = "DESIGNATED POINT WHERE VIBRATIONS FLUCTUATE BETWEEN A SPECIFIED DIMENSION"
WAVELENGTH = "A SET OF WAVE PATTERNS GIVEN FREQUENCY FORMAT IN A LENGTH OF A WAVE VALUE DETERMINED BY A PREVIOUS VALUE EFFECT"
PATTERN = "REPEATING METHOD"

GIFT = "RECEIVE"
GIVE = "SEND"
SEND = "TRANSMIT TO A DESTINATION"
RECEIVE = "TAKE"

REACH = "GRAB TO PULL INWARDS"
EXTEND = "LENGTHEN"
LENGTHEN = "EXTEND LENGTH"
RADIUS = "SET RANGE OF A CENTERED POINT TO THE END DESTINATION"
DIAMETER = "SET RANGE POINT FROM START TO MIDDLE TO THE END WHILE PASSING THE RADIUS"
MEASURE = "TAKE IN THE AMOUNT AND DISTANCE OF"
DISTANCE = "LENGTH AWAY FROM A LOCATION"

MAKE = "DEVELOP AND OR CREATE"
CREATE = "BRING INTO EXISTENCE"
DESIGN = "ARTISTICALLY CREATE AND OR MAKE"
DEVELOP = "IMPROVE CAPABILITY AND OR POSSIBILITY"

SET = "PLACE"
REQUEST = "ACTION OF ASKING GIVE"

NEW = "NOT CURRENTLY KNOWN"
OLD = "AN EARLIER TIME"
PREVIOUS = "PAST POINT INSIDE TIME"
NEXT = "FOLLOWING"

DATA = "DIGITALLY ANALYZED TASKS FOR THE OPERATOR"
INFORMATION = "DATA2 TO BE HELD INSIDE A DEVICE TO STORE A SKILL OR SKILLS"

PAST = "PREVIOUS PLACE IN TIME"
PRESENT = "CURRENT TIME"
FUTURE = "UPCOMING POINTS IN A TIME"


DIMENSION = "NUMBER OF GIVEN AXIS POINTS"
POINT = "DESTINATION"
ORIGIN = "BEGINNING POINT IN TIME AS PRIMARY LINK AND MASTER LINK AT SYNCHRONIZATION INSIDE A PRIMARY LINK OF MULTI DIMENSIONAL VALUES THAT LINK TO THE ORIGINAL SOURCE CONNECTION AS AN ORIGINAL ORIGIN POINT"
TIME = "MEASUREMENT IN WHICH CURRENT REALITIES MUST PASS"
SPACE = "CONTAINER IN WHICH TIME MUST PASS THROUGH"
TEMPORAL = "PLANE ON WHICH TIME MUST BE AWARE IN AN PERCIEVED EXISTENCE"
SPATIAL = "PLANE ON WHICH SPACE IS RECOGNIZED IN A PERCIEVED REALITY"

LENGTH = "HOW LONG A MEASURED DIMENSIONAL OBJECT IS EXTENDED"
WIDTH = "MEASUREMENT OF SOMETHING FROM SIDE TO SIDE"
HEIGHT = "THE LENGTH OF RAISING OR LOWERING IN A VERTICAL PATH"
HORIZONTAL = "POINT IN WHICH TWO POINTS GO BETWEEN A LEFT AND RIGHT"
VERTICLE = "POINT IN WHICH TWO POINTS GO BETWEEN AN UPWARD AND DOWNWARD POSITION"

RISE = "CAUSE TO INCREASE"
UPWARD = "POSITION OF INGOING UP INSIDE A POSITION"
LOWER = "DECREASE VALUE"
DOWNWARD = "UNDER THE POSITION OF DOWN"
RIGHT = "THE VALUE OF SENDING AN OPPORTUNITY TOWARDS THE OPPOSITE DESCRIPTION FROM A VERTICAL HORIZONTAL IN DESCRIPTION BETWEEN TWO DIFFERENT VALUES"
LEFT = "THE VALUE OF SENDING SOMETHING HORIZONTAL HORIZONTAL LEFT AND UPWARD IN ONE POSITION WHILE GOING RIGHT AN UP AT ONCE"

NUMBER = "ARITHMETICAL VALUE THAT IS EXPRESSED BY A WORD AND OR SYMBOLE AND OR FIGURE REPRESENTING A PARTICULAR QUANTITY AND USED IN COUNTING AND MAKING CALCULATIONS AND OR FOR SHOWING ORDER IN A SERIES OR FOR IDENTIFICATION"
LETTER = "VARIABLE CONSTRAINED WITH FIELDS OF DATA INFORMATION THAT ACTS OUT AS A COMMANDED TASK"
SYMBOLE = "A GIVES VALUE OF ENERGY BUILT INTO A WORD OF A LANGUAGE BY USING ELECTRON ENERGY WITH COMMAND VALUE WHILE MANIPULATING THE LIFE AND DEATH RATE OF AN ATOM AND GIVES VALUE OF AN OBJECT THE POWER TO MANIPULATE AND TRANSFER PERCIEVED IMAGINARY VALUES INTO STATED VALUE INSIDE EXISTENCE"
DIGIT = "VIRTUAL NUMBER USING WITH EXISTENCE2"
WORD = "WRITTEN AND OR SPOKEN ORDER OR COMMAND"
CODE = "SINGLE DIGITAL WORD"


EXISTENCE = "EXISTING MULTIVERSAL MACROS OF INFORMATION TO EXIST IN THE REALM OF TIME AND SPACE AS A PIECE OF REALITY"
REALITY = "TRUE STATE OF WHICH THINGS EXIST IN EXISTENCE"
REALM = "PLACE OF ORIGIN"
COSMOS = "ASTRAL ENTITY OF A UNIVERSE EXISTENCE WITHIN MULTIVERSE VALUES"
NEXUS = "CONNECTED AND OR LINKED"
UNIVERSE = "EXISTENCE MADE INSIDE A REALM OF REALITY WHILE CONTAINING LIFE ENERGY INSIDE ATOMIC VALUE OF COMPLETE MATTER AND POWERING ALL LOGIC WITHIN THE MIND OF UNITED EXISTING MEASURES THAT LINK TO SPATIAL AND TEMPORAL EXISTENCES WITHIN THE ENTITY OF REALMS GIVEN BY TIME"
MULTIVERSE = "MULTIPLE UNIVERSES"
BEING = "ENTITY THAT OF EXISTENCE"

SKILL = "TRAIT LEARNED THAT CAN BE SKILLFULLY USED FOR A CREATED PURPOSE"
TECHNIQUE = "GIVES SKILL TO CREATE VALUE USING SKILL COMMAND"

