from Language_Early_Stage import *
MATHEMATICAL_RESTRICTIONS = "A SET AMOUNT OF ACCESS POINTS THAT ARE NOT ACCESSIBLE TO THE OBJECT"
MATHEMATICAL_BOUNDARIES = "A SPECIFIC SET OF PARAMETERS GIVEN TO AN OBJECT TO FOLLOW A SPECIFIC SET OF MATHEMATICAL_RESTRICTIONS"
MATHEMATICAL_LIMITERS = "A SET OF LIMITS GIVEN TO AN OBJECT TO FOLLOW A SPECIFIC SET OF MATHEMATICAL_BOUNDARIES OR MATHEMATICAL_RESTRICTIONS"

